### PR TITLE
mkosi: having a "defaults" file is optional, hence conditionalize MKOSI_DEFAULT

### PR DESCRIPTION
**Pull request by poettering**
Follow-up for b067223c0de3ca814abac0ba6459d4916fd15746

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Lgtm

**Comment by LukeShu** [comment]
I'm not sure why I was CC'd on this, but LGTM?

**Comment by poettering** [comment]
sorry, @LukeShu. I wanted to cc @purpleidea but github autocomplete fucked with my brain, because "Shubin" resolved to your nick...

**Pull request merged**
