### PR TITLE
manifest: don't assume the size field to be valid on deb systems

### PR DESCRIPTION
**Pull request by behrmann**
@dellgreen Can you check whether this fixes your issue?

Fixes: 977

### CODE REVIEW

**Comment by dellgreen** [comment]
testing the change now...

**Comment by dellgreen** [comment]
@behrmann , yep that all builds fine now thank you. :+1:

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by dellgreen** [comment]
I don't believe the Fedora CI failure is related to this fix.

**Comment by behrmann** [comment]
It's not. We currently don't have tests exercising the manifest (even so, having a test would not have found this bug earlier, as regular Debian packages all seem to have this field)

**Pull request merged**
