### PR TITLE
Apply args.environment to all run() and run_workspace_command() calls

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Let's make sure every command we run in or outside of image we're
building inherits the environment variables specified in the Environment
option.

### CODE REVIEW

**Comment by behrmann** [comment]
Sorry, somehow I forgot about this one. I thought it had been merged already.

Only had a quick look. Is my understanding correct, that you populate `os.environ` from `args.env`, so that `run` always sees everything from `args.env` (and `env` passed as parameter at the call site) as well? With the rest being some cleanup so that environments are always set from `args.env` and some `env` parameter? If so, then I think that should be fine. I don't think this should provide any footguns that weren't there before and it makes the code cleaner.

**Comment by behrmann** [comment]
I haven't thought too deeply about this, though. It might warrant a news entry.

**Comment by DaanDeMeyer** [comment]
> Only had a quick look. Is my understanding correct, that you populate os.environ from args.env, so that run always sees everything from args.env (and env passed as parameter at the call site) as well? With the rest being some cleanup so that environments are always set from args.env and some env parameter? If so, then I think that should be fine. I don't think this should provide any footguns that weren't there before and it makes the code cleaner.

Yes, I'll add a comment to explain that when we copy the stuff to os.environ. I'll also add a NEWS entry and I'll extend the documentation for the option.

**Comment by keszybz** [comment]
> Only had a quick look. Is my understanding correct, that you populate `os.environ` from `args.env`, so that `run` always sees everything from `args.env` (and `env` passed as parameter at the call site) as well? With the rest being some cleanup so that environments are always set from `args.env` and some `env` parameter? If so, then I think that should be fine. I don't think this should provide any footguns that weren't there before and it makes the code cleaner.

IMO this should be part of the commit message.

**Comment by DaanDeMeyer** [comment]
> I don't think this is a change for the better, because it removes a separation that is generally clean and useful. What is the justification for the change?

I was thinking about how mkosi-initrd would set `KERNEL_INSTALL_BYPASS=1`, which wouldn't work at the moment because the environment setting isn't applied to the environment when we execute the distro's package manager. So I figured we should apply the environment to those run() calls so that we can influence them by setting environment variables. I took that reasoning a bit further and figured every command we run might benefit from this which led to the current PR.

It might be the wrong approach though because it allows for quite a bit of interference with how we execute commands. It might be better to set KERNEL_INSTALL_BYPASS conditionally in mkosi itself (it'll only work on distros that have recent kernel-install though)

**Comment by DaanDeMeyer** [comment]
Sounds good let's close this

**Pull request closed without merging**
