### PR TITLE
Support Ukify config

### PR DESCRIPTION
**Pull request by MariusSchiffer**
Checks for existence of /etc/kernel/uki.conf and gives this to ukify.

### CODE REVIEW

**Comment by behrmann** [comment]
I don't think we should add this specific option. There's sure going to be more of them, but if there's a config file in a standard location (that then can contain e.g. the splash option) we should include `--config /path/to/config/file`.

**Comment by MariusSchiffer** [comment]
@behrmann Would that be read again on incremental builds? I'm a bit confused on what `state.pkgmngr` does.

**Comment by MariusSchiffer** [comment]
Also I just noticed: Ukify is of course not run in the image itself. Without a specified working directory, it's kinda hard to specify paths in the UKI config file. Can I add a `cwd`?

**Comment by MariusSchiffer** [comment]
Okay, works wonderfully. I added a little bit of documentation. Example section seemed to fit the best.

**Comment by behrmann** [comment]
Thanks for the contribution, @MariusSchiffer!

**Pull request merged**
