### PR TITLE
Update Unit Test CI for Pytest

### PR DESCRIPTION
**Pull request by gsegatti**
Adding sudo to the "Unit Tests" with Pytest portion of the CI, in order to allow using Mkosi's commands with root privilege when testing.

### CODE REVIEW

**Comment by behrmann** [comment]
Haven't yet looked at the WIP stuff, but is there a reason to use `sudo` for unit tests? I think it much preferable, if the unit tests could be run without privileges.

**Comment by gsegatti** [comment]
> Hi Behrmann, let me know if this makes sense:
Currently, I'm building an abstraction that allows building/booting and running commands inside a Mkosi generated image from a python class. In order to build/boot an image we will necessarily go through the check_root() function inside run_verb on __init__.py.
Therefore, without sudo die() will be invoked. If I simply remove the check_root() function, execution will still be stopped due to privileges in init_namespace() -> unshare().

If there's a smarter way of doing this, please, let me know.

**Comment by gsegatti** [comment]
> I see. I guess that is #894? I'll have a look at it tomorrow. If it's #894 we're talking about it would be great if you could write a short description there to see where this is supposed to go.

Yes! I'll write it in the meantime.

**Comment by behrmann** [comment]
Just read the rationale in #894 and for that it will be necessary to run those tests with elevated privileges, that much is true. Mark the integration tests (or all actually using mkosi or parts that n) as skip if EUID isn't 0 and I think that's alright.

**Comment by gsegatti** [comment]
Good suggestion, I've added a skipif() to the pytest file.

**Pull request closed without merging**
