### PR TITLE
Seed package manager config

### PR DESCRIPTION
**Pull request by behrmann**
This is an idea how to address #1603. As argued there, I think skeletons are a sensible solution for this, since there is little point in having skeletons except to preseed config for the package manager, therefore I also don't think it's necessary to have a separate config for this, because either people will not want to update the image (and not care about having the same package manager config in the image as to generate it or they will already clean it up in some postinst) or they will want the same config in the image as to generate it, if they want to be able to update the image.

What this PR does, is to move the package manager config to generate the image into a separate subdirectory below the workspace and moves the files in there into their places where they should be by default, i.e. make it a normal filesystem tree. 

It still needs a few tweaks so that the package manager config can be extended with config from the skeletons (e.g. reading trusted keys for Debian), but it should allow us to remove some config of our own by punting it down to the skeletons (e.g. `repo_dirs`, which is not yet fully removed because I haven't thought about how to best change the pacman config for Arch).

For now this is a discussion piece, whether this is the way to go.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
I would still prefer to decouple copying the package manager configuration files into the image from this. What about using the directories from --package-manager-tree (or w.e. it is called) if it is provided and falling back to the skeleton trees otherwise? And then if the relevant directory/tree exists in the package manager directory or skeleton tree, we use that and if it doesn't, we fall back to our builtin default?

**Comment by behrmann** [comment]
> --package-manager-tree  

Not sure which option, you mean. The closest match would we `RepositoryDirectories=`, but that has a much narrower scope and I think it's actually something we can remove with this approach.

> I would still prefer to decouple copying the package manager configuration files into the image from this.

I guess we need to answer the question what skeleton trees are for. What I describe above are my use cases, so maybe I'm a bit myopic when it comes to this, but my thinking is that skeleton trees are there to preseed the tree before the package manager acts on it. In my use cases there two reasons to do this:
- configure the package manager (which stopped working when the package manager invocations started to happen from the outside and had some edge cases before then, too).
- preempt postinst scriptlets from packages from doing things (if that's supported in the first place)

This PR should reenable the first use case.

In both cases I want to have those files from the skeleton tree in the final image as well, i.e. if we had another option for this, it would in my use case have the same value as the skeleton tree, but if those files shouldn't end up in the final, they can be cleaned up in finalize. Alternatively we can still add a new option after the fact and default it to same value as the skeleton tree and give people an opt out of this behaviour once we see it's necessary.

**Comment by behrmann** [comment]
Okay... While removing the `--repo-dir` option I found a valid use case: the initrd shouldn't contain the skeletons, but use the config. I'll rework it as mentioned above.

**Comment by gdiscry** [comment]
I posted my general opinion in #1603, but FYI I like what you are doing here.

**Pull request closed without merging**
