### PR TITLE
Fix failure using BaseImage with a filesystem image

### PR DESCRIPTION
**Pull request by reubeno**
When `BaseImage` / `--base-image` are pointed at a root filesystem image, the image gets attached to a loopback device, but the filesystem is not mounted and subsequent attempts to create an overlay atop the loop device fail. This also adjusts logic in `attach_image_loopback` to cope with filesystem (i.e., non-disk) images that will have no partition table.

_Doesn't quite address the specific case in #1028 (where the base image is a GPT disk image as opposed to a filesystem image of the root partition), but related. If there is desire to support that case in the future, then mkosi probably can't safely assume that the partition structure of the base image is the same as that of the output image._

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Sorry for the late response, I'm busy getting systemd-repart to a point where we can use it in mkosi, at which point a lot of this logic will change drastically, so I'm not super inclined to spend too much effort in what's currently used in mkosi. Are you fine with keeping this fix in a fork for now?

**Comment by reubeno** [comment]
Thanks for taking a look at this. I appreciate the ongoing work to push disk/partitioning work to systemd-repart, so if you think the right call is to delay on this, then I'll hold onto this in my fork.

With that said, I'd expect that there will still need to be some logic added to mount the rootfs of an input base image (separate from the existing logic that handles the input base image just being a dir)... unless you're thinking that would be pushed onto the caller as a requirement before invoking `mkosi`?

**Comment by DaanDeMeyer** [comment]
@reubeno We've just merged #1276 which significantly changes how this works, can you verify that this is still a problem?

**Comment by DaanDeMeyer** [comment]
Closing for now, @reubeno let me know if this is still a problem on the latest commit. I haven't been testing --base-image really since I'm still planning bigger changes for it but in the current version I can take a look at it if it's not working

**Pull request closed without merging**
