### PR TITLE
gentoo: add gnu-efi USE flag to build systemd-boot

### PR DESCRIPTION
**Pull request by behrmann**
Not sure this is the right flag, but the first thing that a minute of googling turned up, since the CI failures for Gentoo have been bugging me.

/cc @257

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Seems not? We can disable gentoo again until @257 can take a look

**Comment by behrmann** [comment]
Well, worth a try :)

I do think our Gentoo CI needs some more love. I just scrolled through the logs to see whether I'd notice something amiss and disregarding the weird empty screen in between there are file collissions for
- `/tmp/mkosi-root/bin/bzcat`
- `/tmp/mkosi-root/bin/bzunzip2`
- `/tmp/mkosi-root/bin/bzip2`
- `/bin/cpio`
and the systemd build complaining about missing kernel sources and therefore using the installed kernel for feature detection - which will probably be a bit weird since that's a Ubuntu kernel. All in all, cross-building Gentoo might need a bit more attention.

**Comment by 257** [comment]
[renamed to boot](https://github.com/gentoo/gentoo/commit/c5317b6f2795219eef67b0453c5e72a72e3d8be4)

**Comment by 257** [comment]
> Well, worth a try :)
> 
> I do think our Gentoo CI needs some more love. I just scrolled through the logs to see whether I'd notice something amiss and disregarding the weird empty screen in between there are file collissions for
> 
> * `/tmp/mkosi-root/bin/bzcat`
> * `/tmp/mkosi-root/bin/bzunzip2`
> * `/tmp/mkosi-root/bin/bzip2`
> * `/bin/cpio`

where do you see this?

>   and the systemd build complaining about missing kernel sources and therefore using the installed kernel for feature detection - which will probably be a bit weird since that's a Ubuntu kernel. All in all, cross-building Gentoo might need a bit more attention.

that's a bug. do we have 

> [renamed to boot](https://github.com/gentoo/gentoo/commit/c5317b6f2795219eef67b0453c5e72a72e3d8be4)

wait, we are passing boot, where do you see gnu-efi?

**Comment by 257** [comment]
ok, i miss understood. `boot` is the correct flag, see the earlier commit i posted. please close.

**Comment by DaanDeMeyer** [comment]
@257 Can you figure out what's going wrong with the CI then? We can't find systemd-boot at the expected path.

**Comment by 257** [comment]
> @257 Can you figure out what's going wrong with the CI then? We can't find systemd-boot at the expected path.

which action failed? any of them?

**Comment by behrmann** [comment]
> ok, i miss understood. boot is the correct flag, see the earlier commit reference from gentoo/gentoo i posted. please close.

Ok, so that's doubly wrong, then :) The gentoo wiki called the flag `gnu-efi`, and `gnuefi` was supposedly correct in the past. We do use `boot` at the moment, but that's also not it.

> where do you see this?

https://pipelines.actions.githubusercontent.com/serviceHosts/b8aae0cd-0427-4449-98e3-1770240ec56a/_apis/pipelines/1/runs/11810/signedlogcontent/36?urlExpires=2023-07-19T14%3A17%3A33.4284712Z&urlSigningMethod=HMACV1&urlSignature=MIkFxvZ0S8JQd8%2FS7Y9vkcNvpqR8vVAl0%2Fca6Pk5SU8%3D

Pretty far down that log

> which action failed? any of them?

All of them :) (Gentoo anyway)

That's because as Daan pointed out, systemd-boot is not where it's expected. My assumption was, that a use flag was missing (apparently wrong) or it's not built for some other reason.

**Comment by 257** [comment]
ok, i see, fix in a bit.

**Comment by 257** [comment]
well, whitelisting `sys-apps/systemd-999` (built from git) was lost somewhere on the way. we needed that for `ukify`.
does `systemd-253` come with `ukify`?

**Comment by 257** [comment]
> well, whitelisting `sys-apps/systemd-999` (built from git) was lost somewhere on the way. we needed that for `ukify`. does `systemd-253` come with `ukify`?

i would still keep it at `sys-apps/systemd-9999`, there might have been other reasons for going with git version, like `systemd-repart` version.

**Comment by 257** [comment]
> > ok, i miss understood. boot is the correct flag, see the earlier commit reference from gentoo/gentoo i posted. please close.
> 
> Ok, so that's doubly wrong, then :) The gentoo wiki called the flag `gnu-efi`, and `gnuefi` was supposedly correct in the past. We do use `boot` at the moment, but that's also not it.

no! it's the matter of version we're merging.

**Comment by 257** [comment]
fix is trivial for this but disable Gentoo test for now; i noticed we're mixing configs with host. profile is wrong... we should have tested 'Gentoo fixes' properly.

**Comment by DaanDeMeyer** [comment]
@257 You need to run `chroot` now from the debug shell to get into the stage 3 snapshot.

**Comment by 257** [comment]
> chroot emerge info

that just did something odd here:
```
sh-5.2# chroot emerge info
!!! /etc/portage/binrepos.conf is missing (or PORTAGE_BINHOST is unset), but use is requested.

 * IMPORTANT: 10 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

!!! /etc/portage/binrepos.conf is missing (or PORTAGE_BINHOST is unset), but use is requested.
Calculating dependencies... done!
Dependency resolution took 1.67 s.


>>> Verifying ebuild manifests

>>> Emerging (1 of 5) app-eselect/eselect-vi-1.2::gentoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
 * eselect-vi-1.2.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                          [ ok ]
>>> Unpacking source...
>>> Unpacking eselect-vi-1.2.tar.gz to /var/tmp/portage/app-eselect/eselect-vi-1.2/work
>>> Source unpacked in /var/tmp/portage/app-eselect/eselect-vi-1.2/work
>>> Preparing source in /var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2 ...
 * Running eautoreconf in '/var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2' ...
 * Running 'aclocal --system-acdir=/var/tmp/portage/app-eselect/eselect-vi-1.2/temp/aclocal' ...                                                                                                              [ ok ]
 * Running 'autoconf --force' ...                                                                                                                                                                             [ ok ]
 * Running 'automake --add-missing --copy --foreign --force-missing' ...                                                                                                                                      [ ok ]
 * Running elibtoolize in: eselect-vi-1.2/
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2 ...
 * econf: updating eselect-vi-1.2/config.sub with /usr/share/gnuconfig/config.sub
 * econf: updating eselect-vi-1.2/config.guess with /usr/share/gnuconfig/config.guess
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/eselect-vi-1.2 --htmldir=/usr/share/doc/eselect-vi-1.2/html --libdir=/usr/lib64
checking for a BSD-compatible install... /usr/lib/portage/python3.11/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vi.eselect
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2 ...
make -j8
make: Nothing to be done for 'all'.
>>> Source compiled.
>>> Test phase [not enabled]: app-eselect/eselect-vi-1.2

>>> Install app-eselect/eselect-vi-1.2 into /var/tmp/portage/app-eselect/eselect-vi-1.2/image
make -j8 DESTDIR=/var/tmp/portage/app-eselect/eselect-vi-1.2/image install
make[1]: Nothing to be done for 'install-exec-am'.
make[1]: Entering directory '/var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2'
 /usr/bin/mkdir -p '/var/tmp/portage/app-eselect/eselect-vi-1.2/image/usr/share/eselect/modules'
 /usr/lib/portage/python3.11/ebuild-helpers/xattr/install -c -m 644 vi.eselect '/var/tmp/portage/app-eselect/eselect-vi-1.2/image/usr/share/eselect/modules'
make[1]: Leaving directory '/var/tmp/portage/app-eselect/eselect-vi-1.2/work/eselect-vi-1.2'
>>> Completed installing app-eselect/eselect-vi-1.2 into /var/tmp/portage/app-eselect/eselect-vi-1.2/image

 * Final size of build directory: 880 KiB
 * Final size of installed tree:    8 KiB


>>> Installing (1 of 5) app-eselect/eselect-vi-1.2::gentoo

>>> Completed (1 of 5) app-eselect/eselect-vi-1.2::gentoo

>>> Emerging (2 of 5) dev-libs/libsodium-1.0.18_p20220618::gentoo
 * libsodium-1.0.18_p20220618.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking libsodium-1.0.18_p20220618.tar.gz to /var/tmp/portage/dev-libs/libsodium-1.0.18_p20220618/work
>>> Source unpacked in /var/tmp/portage/dev-libs/libsodium-1.0.18_p20220618/work
>>> Preparing source in /var/tmp/portage/dev-libs/libsodium-1.0.18_p20220618/work/libsodium-stable ...
 * Applying libsodium-1.0.10-cpuflags.patch ...
patching file configure.ac
Hunk #1 succeeded at 438 (offset 94 lines).
Hunk #2 succeeded at 454 (offset 94 lines).
Hunk #3 succeeded at 528 with fuzz 1 (offset 130 lines).
Hunk #4 succeeded at 563 (offset 144 lines).                                                                                                                                                                  [ ok ]
^C

Exiting on signal 2

sh-5.2#
```

**Comment by 257** [comment]
you mean `chroot emerge --info`

**Comment by 257** [comment]
fix is waiting at https://github.com/systemd/mkosi/pull/1685

**Comment by 257** [comment]
> https://pipelines.actions.githubusercontent.com/serviceHosts/b8aae0cd-0427-4449-98e3-1770240ec56a/_apis/pipelines/1/runs/11810/signedlogcontent/36?urlExpires=2023-07-19T14%3A17%3A33.4284712Z&urlSigningMethod=HMACV1&urlSignature=MIkFxvZ0S8JQd8%2FS7Y9vkcNvpqR8vVAl0%2Fca6Pk5SU8%3D

it says URI expired!

**Comment by 257** [comment]
>   and the systemd build complaining about missing kernel sources and therefore using the installed kernel for feature detection - which will probably be a bit weird since that's a Ubuntu kernel.

where do you see this?

**Comment by 257** [comment]
> well, whitelisting `sys-apps/systemd-999` (built from git) was lost somewhere on the way. we needed that for `ukify`. does `systemd-253` come with `ukify`?

i see, my PR was on top of Gentoo-fixes:
https://github.com/systemd/mkosi/pull/1650/commits/f0891fa45dc551622f8f5987fe4851aa7beeab24#diff-e89c10e3e1a25022797c92a8ba44fda97927bbb6a59220a48084d3bf70378de8R138

**Comment by 257** [comment]
@DaanDeMeyer can you review that PR please?

**Comment by behrmann** [comment]
Obviated by #1685

**Pull request closed without merging**
