### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
Mea culpa. @DaanDeMeyer you probably want to look at this one before the others.

**Comment by behrmann** [comment]
What a wonderful coincidence. :) I was just typing those very same fixes because I wondered how my changes in #788 broke the tests until I noticed they are broken on `main`.

**Review by behrmann — APPROVED** [review]

**Comment by keszybz** [comment]
One more obvious fixlet.

**Comment by DaanDeMeyer** [comment]
CI fails but that's because of pyright, let's merge

**Pull request merged**
