### PR TITLE
ci: Remove shellcheck step

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
We don't have any scripts to check anymore.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Not sure how #923 got past CI since it should have failed on the shellcheck step.

**Comment by DaanDeMeyer** [comment]
unit-test workflow passed so let's merge to fix CI

**Comment by behrmann** [comment]
> We don't have any scripts to check anymore.

Not quite true, there's still `mkosi/resources/arch/kernel_{add,remove}.sh`, which are now unused, so those might be removed as well.

**Comment by DaanDeMeyer** [comment]
So the glob wasn't working then? I'm confused

**Comment by DaanDeMeyer** [comment]
https://github.com/systemd/mkosi/pull/936 fixes it

**Pull request merged**
