### PR TITLE
fedora: Default to the minimal authselect profile if authselect is installed

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by poettering** [comment]
really new authselect has a "home" feature one can enable. we should enable that.

**Comment by DaanDeMeyer** [comment]
Let's wait with doing that until it's more widespread. We can test it out in the systemd repo by enabling it in the postinstall script.

**Comment by behrmann** [comment]
Is `authselect` something like the Debian PAM config snippets>

**Comment by DaanDeMeyer** [comment]
No idea, I don't know how Debian handles this

**Comment by poettering** [comment]
> Let's wait with doing that until it's more widespread. We can test it out in the systemd repo by enabling it in the postinstall script.

the snippet should have zero effect unless homed is also used and has an account. the fact that the thing is hidden behind a flag is pretty pointless if you ask me, more a political choice than a technical one, given the stuff is as non-intrusive as it could be.

**Comment by DaanDeMeyer** [comment]
We use home if it's there and minimal otherwise

**Comment by poettering** [comment]
btw, you might just write `/etc/authselect/authselect.conf` directly, and set it to the raw contents:

```
minimal
with-homed
```

and do that ahead of time before invoking dnf. so that the system never comes up with crap config we then later turn off again.

**Pull request merged**
