### PR TITLE
Handle rw and ro kernel command line parameters.

### PR DESCRIPTION
**Pull request by drewmoseley**
Is this the right approach or is there a better way to handle this?

### CODE REVIEW

**Comment by behrmann** [comment]
This would certainly be a way. Could you describe (and maybe open) an issue it fixes? It would still need fixing the tests for the CLI, though.

Another way would be to set bit 60 of the partitions in accordance with the [discoverable partition spec](https://systemd.io/DISCOVERABLE_PARTITIONS/), which might be preferable, but about which I don't have strong opinions.

**Comment by DaanDeMeyer** [comment]
> Another way would be to set bit 60 of the partitions in accordance with the discoverable partition spec, which might be preferable, but about which I don't have strong opinions.

We already do this I think.

I agree some more context on the issue we're fixing here would be nice. I don't see a big harm in adding this though but I'm not familiar with the details of ro/rw.

**Comment by drewmoseley** [comment]
OK.  I'll take a step back and see if I can generate a minimal reproducible issue. It will likely be a few days before I can get to it.

**Comment by behrmann** [comment]
> We already do this I think.
> 

Ah, true, that's what the `read_only` argument in `insert_partition` is for. It's only used for squash images and verity partitions, though and not further exposed.

**Comment by drewmoseley** [comment]
I created an[ issue here.](https://github.com/systemd/mkosi/issues/543)

Based on the comment above about squashfs and verity I guess this is not surprising.

**Comment by drewmoseley** [comment]
This has been adapted per the [discussion here](https://github.com/systemd/mkosi/issues/543). I also added a typo fix to the README.

I'll look into the CI failure next.

**Comment by DaanDeMeyer** [comment]
This looks a lot better but I would add back 'rw' to the kernel command line if args.read_only is not set. That makes sure we don't change behavior for the majority of use cases.

**Comment by DaanDeMeyer** [comment]
LGTM, thanks for the contribution!

**Pull request merged**
