### PR TITLE
Update some Package Versions to latest

### PR DESCRIPTION
**Pull request by pheiduck**
missing dnf and rpm

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
pacman is now packaged as an xz archive instead of gz so that should be changed in the url to avoid 404 errors when trying to build pacman

**Comment by pheiduck** [comment]
> pacman is now packaged as an xz archive instead of gz so that should be changed in the url to avoid 404 errors when trying to build pacman

Yup, you right, forgot to change it. Will fix it

**Comment by pheiduck** [comment]
@DaanDeMeyer rework is done on my side.

**Comment by pheiduck** [comment]
`meson.build:111:8: ERROR: Problem encountered: A Python3 binding requires a GObject introspection. `

Do not have a solution for this

**Comment by DaanDeMeyer** [comment]
Try installing python3-gi

**Comment by pheiduck** [comment]
Close this pr because I can not fix the problem

**Pull request closed without merging**
