### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Split out of #2956

### CODE REVIEW

**Review by behrmann — APPROVED** [review]

**Comment by behrmann** [comment]
CI failures are unrelated. Keyrings for Arch and Fedora, a busy device for opensuse/debian in the luks initrd test.

**Comment by evverx** [comment]
@DaanDeMeyer I took a look at https://github.com/systemd/mkosi/actions/runs/10492889150/job/29066148272 and it seems the actions are run with tokens that has all sorts of permissions:
```sh
GITHUB_TOKEN Permissions
  Actions: write
  Attestations: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```
Would it be OK if I flipped https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions to make it read-only? It was set up a long time ago in the systemd and systemd-stable repositories (and all the new repositories come with read-only tokens by default) but since I didn't pull mkosi I probably skipped it at the time. Looks like the branch protection rules aren't set up either.

(On a unrelated note GitHub actions keep on giving https://unit42.paloaltonetworks.com/github-repo-artifacts-leak-tokens/ :-))

**Comment by DaanDeMeyer** [comment]
> @DaanDeMeyer I took a look at https://github.com/systemd/mkosi/actions/runs/10492889150/job/29066148272 and it seems the actions are run with tokens that has all sorts of permissions:
> ```sh
> GITHUB_TOKEN Permissions
>   Actions: write
>   Attestations: write
>   Checks: write
>   Contents: write
>   Deployments: write
>   Discussions: write
>   Issues: write
>   Metadata: read
>   Packages: write
>   Pages: write
>   PullRequests: write
>   RepositoryProjects: write
>   SecurityEvents: write
>   Statuses: write
> ```
> Would it be OK if I flipped https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions to make it read-only? It was set up a long time ago in the systemd and systemd-stable repositories (and all the new repositories come with read-only tokens by default) but since I didn't pull mkosi I probably skipped it at the time. Looks like the branch protection rules aren't set up either.
> 
> (On a unrelated note GitHub actions keep on giving https://unit42.paloaltonetworks.com/github-repo-artifacts-leak-tokens/ :-))

Sounds good to me. If we're running with too many permissions we should drop them.

**Comment by evverx** [comment]
Done.

(I didn't set up any branch protection rules but I think rules like https://github.com/systemd/systemd/rules/261437?ref=refs%2Fheads%2Fmain should work here too. They restrict deletions and block force pushes)

**Comment by DaanDeMeyer** [comment]
> Done.
> 
> (I didn't set up any branch protection rules but I think rules like https://github.com/systemd/systemd/rules/261437?ref=refs%2Fheads%2Fmain should work here too. They restrict deletions and block force pushes)

We can add those as well I think. mkosi development is the same as systemd so we don't push straight to main except when we do releases.

**Comment by evverx** [comment]
Got it. I added https://github.com/systemd/mkosi/rules/1477419?ref=refs%2Fheads%2Fmain

**Comment by DaanDeMeyer** [comment]
Thanks!

**Pull request merged**
