### PR TITLE
mkosi-initrd: Copy md and dm udev rules from dracut

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Until these are upstreamed into their corresponding projects, let's carry the rules in mkosi-initrd.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
I'm not sure how to properly attribute these? Do I need to put a GPL v2 notice in there pointing back to dracut somehow?

**Comment by DaanDeMeyer** [comment]
Replaces #2056

**Comment by bluca** [comment]
> I'm not sure how to properly attribute these? Do I need to put a GPL v2 notice in there pointing back to dracut somehow?

For clarity an SPDX line first and a link to the original second won't hurt

**Review by behrmann — APPROVED** [review]

**Review by keszybz — COMMENTED** [review]
FTR, I think that the first of those two files should be replaced by dropping `initrd-udevadm-cleanup-db.service` service, and the second should be moved to `mdadm`.

**Pull request merged**
