### PR TITLE
Add erofs and fat utils to initrd

### PR DESCRIPTION
**Pull request by septatrix**
These provide the respective fsck progs

### CODE REVIEW

**Comment by behrmann** [comment]
This needs a bump in the initrd size used in tests, apart from that LGTM.

**Comment by septatrix** [comment]
The opensuse/arch seems to be failing due to some dnf failures which seems unrelated:

```
2024-10-11T11:34:11.9403330Z Failed:
2024-10-11T11:34:11.9403750Z   dbus-1-common-1.14.10-3.1.noarch                                              
2024-10-11T11:34:11.9404427Z   system-group-hardware-20170617-25.4.noarch                                    
2024-10-11T11:34:11.9405111Z   system-group-kvm-20170617-25.4.noarch                                         
2024-10-11T11:34:11.9405896Z   system-user-lp-20170617-25.4.noarch                                           
2024-10-11T11:34:11.9406269Z 
2024-10-11T11:34:11.9406356Z Cleaning up.
2024-10-11T11:34:11.9406633Z Plugins were unloaded.
2024-10-11T11:34:11.9406802Z 
2024-10-11T11:34:11.9406915Z Traceback (most recent call last):
2024-10-11T11:34:11.9407441Z   File "/usr/lib/python3.12/site-packages/dnf/cli/main.py", line 67, in main
2024-10-11T11:34:11.9407995Z     return _main(base, args, cli_class, option_parser_class)
2024-10-11T11:34:11.9408407Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-11T11:34:11.9408962Z   File "/usr/lib/python3.12/site-packages/dnf/cli/main.py", line 106, in _main
2024-10-11T11:34:11.9409435Z     return cli_run(cli, base)
2024-10-11T11:34:11.9409706Z            ^^^^^^^^^^^^^^^^^^
2024-10-11T11:34:11.9410197Z   File "/usr/lib/python3.12/site-packages/dnf/cli/main.py", line 130, in cli_run
2024-10-11T11:34:11.9410674Z     ret = resolving(cli, base)
2024-10-11T11:34:11.9410947Z           ^^^^^^^^^^^^^^^^^^^^
2024-10-11T11:34:11.9411463Z   File "/usr/lib/python3.12/site-packages/dnf/cli/main.py", line 183, in resolving
2024-10-11T11:34:11.9412103Z     base.do_transaction(display=displays)
2024-10-11T11:34:11.9412721Z   File "/usr/lib/python3.12/site-packages/dnf/cli/cli.py", line 272, in do_transaction
2024-10-11T11:34:11.9413351Z     raise dnf.exceptions.Error(_('Transaction failed'))
2024-10-11T11:34:11.9413757Z dnf.exceptions.Error: Transaction failed
2024-10-11T11:34:11.9414090Z Error: Transaction failed
```

**Comment by septatrix** [comment]
I must have forgotten to add `--amend` when committing, sorry for not having the commits squashed

**Comment by DaanDeMeyer** [comment]
Ah oops didn't notice, oh well

**Pull request merged**
