### PR TITLE
CI: Add systemd-nspawn boot test

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Let's see how this goes.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
The good thing is expect works. The bad thing is that it doesn't work without an open stdin for some reason. As expected simply adding this to CI is uncovering a host of bugs as well so I'm fixing those as they appear.

**Comment by behrmann** [comment]
Excellent work, @DaanDeMeyer!

**Comment by DaanDeMeyer** [comment]
Switched to pexpect, doesn't suffer from the stdin issue and we can stick to the same programming language used in mkosi itself.

**Comment by DaanDeMeyer** [comment]
@Werkov Any idea what opensuse could be doing that prevents root login? On the other distros we simply remove pam_securetty.so from /etc/pam.d/login which fixes the issue but this doesn't seem to work on opensuse. I tried copying the file from /usr/etc/pam.d/login first but that doesn't seem to work either. Removing /etc/securetty altogether is also not a fix.

**Comment by DaanDeMeyer** [comment]
@ssahani Any chance you could look at the Photon failures? Seems like systemd-networkd-wait-online is failing, even though no network related services should be started since the container is started with --private-networkd (no CAP_NET_ADMIN). See https://github.com/systemd/mkosi/pull/514/checks?check_run_id=990384883#step:6:75

**Comment by behrmann** [comment]
> Any idea what opensuse could be doing that prevents root login without a root password set? 

Maybe as a workaround set a password and funnel it through expect for the login?

**Comment by DaanDeMeyer** [comment]
> Maybe as a workaround set a password and funnel it through expect for the login?

Yeah did that for now. I'd prefer to get all this stuff fixed though. We're already at way too much ifs in the CI imo. Should be green now.

**Comment by behrmann** [comment]
I don't think its too much of a problem setting a root password, is it? It's an edge case we shouldn't worry about. Either root accounts are disabled or they have a password and we can just set one.

**Comment by DaanDeMeyer** [comment]
This is purely anecdotal, but my first experience with mkosi was trying to build an arch image for systemd, trying to boot it, not being able to login as root, trying to set --password '' and still not being able to login. That did annoy me a bit at first so I think its important this works as expected, especially since we explicitly advertise it works in the docs. We're in a pretty good spot right now though, only opensuse is still broken in terms of deleting the root password.

**Comment by DaanDeMeyer** [comment]
Added one more doc fix so not going to wait out CI. I do think depending on the amount of pexpect tests we add that we should eventually run all these under pytest as well so we can run them locally as well if we want to. For now though, let's merge this as its simple and provides a lot of value already.

**Comment by Werkov** [comment]
@DaanDeMeyer (a bit delayed answer) I have no experience with passwordless logins but I traced it down to missing `nullok` in common-auth:pam_unix (I didn't verify it in an actual image though).

**Comment by DaanDeMeyer** [comment]
@Werkov I'll try that out. Thanks for the tip!

**Pull request merged**
