### PR TITLE
centos: Add check that --netdev is always used with EPEL variants

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by behrmann** [comment]
LGTM, but CI is acting up. Maybe a result of #1130 or #1131?

**Comment by DaanDeMeyer** [comment]
Hmm, probably the blkdiscard thing then I'd guess. I'll try to revert and we'll see what happens

**Comment by DaanDeMeyer** [comment]
Let's merge this though

**Comment by DaanDeMeyer** [comment]
@behrmann When merging pull requests with a single commit, please use rebase instead of merge (don't ask me why, systemd policies, multiple commits should have a merge commit though)

**Comment by behrmann** [comment]
Will do!

**Pull request merged**
