### PR TITLE
Ensure user provided cmdline is always last

### PR DESCRIPTION
**Pull request by septatrix**
This is required for `--` to work such that one can stop the kernel from parsing further options and simply passing them as arguments to the init process

Open to suggestions on how to improve this. We could for example first collect all of mkosi's options and then directly before executing qemu append the user provided cmdline. This is just the quickest fix, not necessarily the cleanest ;) It also assumes that nothing depends on the order of the arguments which I am not sure is the case (e.g. what happens if two `systemd.set_credential_binary` with the same name defined - with this change the order would be reversed).

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
@septatrix We can just move the `finalize_extra_command_line_extra()` call further down

**Comment by septatrix** [comment]
> @septatrix We can just move the `finalize_extra_command_line_extra()` call further down

Then we would need to special case some things as e.g. `root=` currently depends on the finalized cmdline

**Comment by DaanDeMeyer** [comment]
@septatrix You can generalize `finalize_kernel_command_line_extra()` to `finalize_kernel_command_line()` and move the if condition at the callsite into the function. Then you can evaluate against `finalize_kernel_command_line()` instead of `kcl` when determining `root=`.

**Comment by septatrix** [comment]
Not sure if I understood your suggestion correctly. I feel like I might have done the exact opposite now...

**Pull request closed without merging**
