### PR TITLE
Use qemu's virtconsole for the serial console

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
edk2 now has a virtio serial driver so let's switch to virtconsole
for the serial console as it's significantly faster compared to the
old ISA serial console.

### CODE REVIEW

**Comment by teknoraver** [comment]
I confirm it works:
```
[root@fedora ~]# w
 17:53:36 up 0 min,  3 users,  load average: 0.18, 0.06, 0.02
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
root     hvc0      17:53    0.00s  0.03s  0.01s w
```

**Comment by teknoraver** [comment]
And it's fast:
```
[root@fedora ~]# time hexdump -vC -n200000 /dev/zero

real	0m0.451s
user	0m0.029s
sys	0m0.418s
```

**Review by behrmann — APPROVED** [review]
Beautiful.

**Comment by rpardini** [comment]
While this does indeed work, for images targeting `ttyS0` or `ttyAMA0` as (real/physical) consoles, this breaks the autologin feature on those consoles (`tty1` still works). I guess at a certain point (eg, Rockchip devices and their console on `ttyS2`) it makes more sense to make autologin consoles configurable somehow. Should I open an issue about this?

**Comment by DaanDeMeyer** [comment]
> While this does indeed work, for images targeting `ttyS0` or `ttyAMA0` as (real/physical) consoles, this breaks the autologin feature on those consoles (`tty1` still works). I guess at a certain point (eg, Rockchip devices and their console on `ttyS2`) it makes more sense to make autologin consoles configurable somehow. Should I open an issue about this?

You can configure autologin with systemd credentials these days on a per tty basis. I would always do that instead of the autologin setting. I'll probably remove it at some point.

**Pull request merged**
