### PR TITLE
don't fail on non-controlling ttys

### PR DESCRIPTION
**Pull request by katexochen**
I run into this issue where the tty is non-controlling and this call failed.

### CODE REVIEW

**Review by DaanDeMeyer — COMMENTED** [review]
This leaves the signal blocked. We need to unblock the signal even if we fail.

**Comment by katexochen** [comment]
Sorry, I'm really not good with the tty stuff. How do I unblock the signal? Should I skip the return and continue with `signal.signal(signal.SIGTTOU, old)`?

**Comment by DaanDeMeyer** [comment]
Yes

**Comment by DaanDeMeyer** [comment]
Please put the raise on a newline like we do everywhere else

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
