### PR TITLE
Fix invoked_as_root initialization

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Review by behrmann — APPROVED** [review]

**Review by behrmann — APPROVED** [review]

**Comment by marc-hb** [comment]
The problem goes way after giant, v25 commit b3a3e7e7fcb2a4e8f ("Introduce mkosi-sandbox and stop using subuids for image builds") which rewrites everything. I don't think v25 is released yet.

This means v23.1 and v24.x are failing. v23 was before 17010a2 and works fine.

**Comment by DaanDeMeyer** [comment]
Yeah we'll release v25 soon which drastically changes all of this. Apologies for the churn, I've been figuring most of this out on the go to find out what works and what doesn't. We try to keep breaking changes to a minimum but don't always succeed

**Comment by marc-hb** [comment]
Should I copy this report to a new, "wontfix; upgrade to future v25" bug for better visibility? This is fatal failure of the latest released version.


> Something must have changed in my DNF configuration recently because that failure is recent...!? v24.3 (and many others) used to work.

I found this on my system. The timestamps look a bit strange; the two files seem to have a different understanding of the word "upgraded"!

```

/var/log/dnf.rpm.log:2024-09-19T15:41:25-0700 SUBDEBUG Upgraded: dnf-4.21.0-1.fc40.noarch
/var/log/dnf.rpm.log:2024-09-19T15:41:26-0700 SUBDEBUG Upgraded: python3-dnf-4.21.0-1.fc40.noarch

/var/log/dnf.log.3:2024-09-19T15:43:03-0700 DEBUG Upgraded: dnf-4.21.1-1.fc40.noarch
/var/log/dnf.log.3:2024-09-19T15:43:03-0700 DEBUG Upgraded: python3-dnf-4.21.1-1.fc40.noarch

/var/log/dnf.rpm.log:2024-12-16T16:37:37-0800 SUBDEBUG Upgraded: dnf-4.21.1-1.fc40.noarch
/var/log/dnf.rpm.log:2024-12-16T16:37:37-0800 SUBDEBUG Upgraded: python3-dnf-4.21.1-1.fc40.noarch

/var/log/dnf.log:2024-12-16T16:38:24-0800 DEBUG Upgraded: dnf-4.22.0-1.fc40.noarch
/var/log/dnf.log:2024-12-16T16:38:24-0800 DEBUG Upgraded: python3-dnf-4.22.0-1.fc40.noarch

```

Also:

```
/var/log/dnf.rpm.log:2024-12-16T16:37:38-0800 SUBDEBUG Upgraded: python3-libdnf-0.73.3-1.fc40.x86_64
/var/log/dnf.rpm.log:2024-12-16T16:37:38-0800 SUBDEBUG Upgraded: libdnf-0.73.3-1.fc40.x86_64

/var/log/dnf.log:2024-12-16T16:35:30-0800 DEBUG ---> Package libdnf.x86_64 0.73.3-1.fc40 will be upgraded
/var/log/dnf.log:2024-12-16T16:35:30-0800 DEBUG ---> Package python3-libdnf.x86_64 0.73.3-1.fc40 will be upgraded
/var/log/dnf.log:2024-12-16T16:38:24-0800 DEBUG Upgraded: libdnf-0.73.4-1.fc40.x86_64
/var/log/dnf.log:2024-12-16T16:38:24-0800 DEBUG Upgraded: python3-libdnf-0.73.4-1.fc40.x86_64
```


I tried to downgrade to dnf 4.19.0  and libdnf 0.73.0 which are still available in dnf (the others are not) but mkosi still fails the same.

**Comment by marc-hb** [comment]
> Should I copy this report to a new, "wontfix; upgrade to future v25" bug for better visibility? This is fatal failure of the latest released version.

Done:
- #3295

**Pull request merged**
