### PR TITLE
Photon OS support

### PR DESCRIPTION
**Pull request by suezzelur**
Known limitations:
- The gpg key is not published on the web, so VMWARE-RPM-GPG-KEY should be present in the host 
- No uefi boot supported yet

### CODE REVIEW

**Comment by johannbg** [comment]
Can anyone create images and access the entire Photon OS repository's ( packages, source code etc ) without having to go through some registration process or paywall like subscription of some sort?

**Comment by johannbg** [comment]
is tdnf available as an package manager in the primary distributions so photon os can be installed on mkosi on arch,debian,fedora and opensuse?

**Comment by poettering** [comment]
hmm, is photon OS a distro that is going to stay? it uses "tdnf", what is that? is that pcakaged anywhere else?

I am not against adding this, just wondering if the distro is big enough and has a future so that we should care?

**Comment by poettering** [comment]
patch looks good otherwise, but needs rebase

if the gpg keys are not downloadable, maybe just commit them here?

**Comment by poettering** [comment]
I guess we can close this now that #357 is merged.

**Pull request closed without merging**
