### PR TITLE
Fix building openSUSE images after RPM upgrade

### PR DESCRIPTION
**Pull request by Werkov**

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Any chance we could build zypper from source as well? I tried it a long time ago but gave up due to zypper's build system not being terribly cooperative. I figure that's a better longterm solution than relying on whatever ancient version is packaged by Ubuntu.

**Comment by behrmann** [comment]
The opensuse CI is failing, but it does look somewhat hopeful, since it builds in the first place and only networkd seems to be missing.

**Comment by Werkov** [comment]
Yeah, it's moved from zypper failure to networkd-failure (which [doesn't affect](https://github.com/systemd/systemd/commit/2e9055ab6a9967880ed12586650970368f7b8640) systemd CI though). I'll debug the zypper/RPM failure first.

**Comment by Werkov** [comment]
So the failure with RPM rpm-4.17.0-release is again apparently the same as in rpm-4.16.0 ([full log](https://github.com/systemd/mkosi/runs/4335989488?check_suite_focus=true#step:9:51)). 

```
2021-11-26 16:35:06 <1> fv-az272-867(32895) [zypp::exec++] ExternalProgram.cc(start_program):259 Executing 'rpmdb2solv' '-r' '/var/tmp/mkosi-iwtnaq2v/root' '-X' '-p' '/var/tmp/mkosi-iwtnaq2v/root/etc/products.d' '-o' '/var/tmp/mkosi-iwtnaq2v/root/var/cache/zypp/solv/@System/solvTtMCcx'
2021-11-26 16:35:06 <1> fv-az272-867(32895) [zypp::exec++] ExternalProgram.cc(start_program):424 pid 32896 launched
2021-11-26 16:35:06 <2> fv-az272-867(32895) [zypp] TargetImpl.cc(buildCache):932   warning: using dummy database, installs not possible
2021-11-26 16:35:06 <2> fv-az272-867(32895) [zypp] TargetImpl.cc(buildCache):932   rpmdb2solv: no error
2021-11-26 16:35:06 <1> fv-az272-867(32895) [zypp::exec++] ExternalProgram.cc(checkStatus):518 Pid 32896 exited with status 1
2021-11-26 16:35:06 <5> fv-az272-867(32895) [zypp] Exception.cc(log):166 TargetImpl.cc(buildCache):945 THROW:    Failed to cache rpm database (1).
```

There is the [patch](https://github.com/rpm-software-management/rpm/commit/0644e4e79c841b03d606fc8bb035ec311f4bfb17) that fixed this for >rpm-4.16.1 and the fix is also present in
rpm-4.17.0-release but it doesn't work with this upstream RPM version.

I'm clueless, @mlschroe do you have any idea why the upstream RPM won't work with your fixup? (Note this is `zypper --root` running on Ubuntu host.)

**Comment by Werkov** [comment]
Closing since a workaround from #878 is in place.

**Pull request closed without merging**
