### PR TITLE
Fix packages and build packages not being installed on Centos and Mageia.

### PR DESCRIPTION
**Pull request by liam-mcb**
Fix build packages not being installed for Centos builds.
Fix packages and build packages not being installed for Mageia builds.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
but CentOS on CI is still failing. Do you need and additional repo?
```
subprocess.CalledProcessError: Command '['yum', '-y', '--config=/home/runner/work/mkosi/mkosi/mkosi.output/.mkosi-pyhjo52k/yum.conf', '--releasever=8', '--installroot=/home/runner/work/mkosi/mkosi/mkosi.output/.mkosi-pyhjo52k/root', '--disablerepo=*', '--enablerepo=base', '--enablerepo=updates', '--enablerepo=extras', '--enablerepo=centosplus', '--enablerepo=epel', '--setopt=keepcache=1', '--setopt=tsflags=nodocs', 'install', 'centos-release', 'tzdata', 'epel-release']' returned non-zero exit status 1.
```

**Comment by liam-mcb** [comment]
CentOS changed their repo names between v7 and 8. #405 
I've been meaning to get around to that.
I've just added a patch to support building CentOS 8 images.
There's still a couple of failing builds because some CentOS EPEL mirrors aren't the most reliable sources.

**Comment by DaanDeMeyer** [comment]
@liam-mcb This looks solid but I want to have a more recent CI run to make sure this still works as expected. Can you do a rebase on master and force push (`git push -f`) to retrigger the CI (Github doesn't seem to let me do that myself).

**Comment by lucasdemarchi** [comment]
@DaanDeMeyer  github actually does allow it if you are part of the developer team. Basically you have to force push to his repo,  liam-mcb/mkosi. Github will notice this is related to a PR open in mkosi and allow you to push to his remote

**Comment by DaanDeMeyer** [comment]
I rebased on master and changed the function names to install_centos_new and install_centos_old. I'll merge this when CI is green.

**Comment by DaanDeMeyer** [comment]
I added another commit to use mirrorlist.fedoraproject.org to get the epel mirrors. That seems to work a lot better (or the current CI run is green by chance, we'll see I guess).

**Pull request merged**
