### PR TITLE
Fixed capitalization of `SignExpectedPcr`

### PR DESCRIPTION
**Pull request by NekkoDroid**
Fixes: #2086

### CODE REVIEW

**Comment by behrmann** [comment]
That's one way of fixing that, but I think it might be better to
```diff
     MkosiConfigSetting(
         dest="sign_expected_pcr",
         metavar="FEATURE",
+        name="SignExpectedPCR",
         section="Validation",
         parse=config_parse_feature,
     )
```
which would leave the user-facing side untouched. Can you give that a test and see whether that change would work for you?

**Comment by NekkoDroid** [comment]
This does work.

The reason I decided to change the documentation was mostly incase someone actually already figure this out and decided to not report it, to not break their config.

But if this is the preferred way I can gladly undo the commit and change the name instead.

**Comment by NekkoDroid** [comment]
I just did a quick search on github and I looks like systemd itself (and some forks) uses the lower case variants: https://github.com/systemd/systemd/blob/main/mkosi.presets/system/mkosi.conf#L48

**Comment by behrmann** [comment]
Then let's stay with that.

**Review by behrmann — APPROVED** [review]

**Pull request merged**
