### PR TITLE
Rename "none" distribution to "custom"

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
"custom" seems a better fit than "none" since there likely still
is a distribution, we just don't support it.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
cc @katexochen can you verify the tests still pass for you with this PR applied?

**Comment by DaanDeMeyer** [comment]
cc @snickl

**Comment by katexochen** [comment]
Thanks for the ping. The PR indeed breaks the tests on NixOS:

```
WARNING  root:config.py:2209 Setting ImageId should be configured in [Output], not [Content].
=========================== short test summary info ============================
FAILED tests/test_config.py::test_parse_load_verb - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_os_distribution - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_parse_config_files_filter - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_compression - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_distribution[custom-custom] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[==-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[==-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[==-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<=-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<=-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[<=-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>=-122] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>=-123] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_match_imageversion[>=-124] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[None-None] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[None-pkgmngr1] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[None-pkgmngr2] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel3-None] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel4-pkgmngr4] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel5-pkgmngr5] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel6-None] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel7-pkgmngr7] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_package_manager_tree[skel8-pkgmngr8] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections0-args0-0] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections1-args1-1] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections2-args2-1] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections3-args3-1] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections4-args4-2] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
FAILED tests/test_config.py::test_wrong_section_warning[sections5-args5-1] - ModuleNotFoundError: No module named 'mkosi.distributions.custom'
======================= 38 failed, 192 passed in 13.19s ========================
```

**Comment by DaanDeMeyer** [comment]
@katexochen I think you got an old version of the branch, can you pull again?

**Comment by katexochen** [comment]
Tests pass on 4f55e04ba521cc6097b32ca4bc1661213968a41a :+1:

**Review by behrmann — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
I still think "custom" conveys the intent better. Even if mkosi isn't the one putting the distro in the image, there still needs to be a distro with an os-release file and such. "none" might give users the idea they can put it in whatever.

**Pull request merged**
