### PR TITLE
Two fixes

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by keszybz** [comment]
Looks reasonable, but the CI is unhappy.

**Comment by keszybz** [comment]
2024-01-11T13:36:39.6415750Z =========================== short test summary info ============================
2024-01-11T13:36:39.6417000Z FAILED tests/test_boot.py::test_boot[disk] - subprocess.CalledProcessError: C...
2024-01-11T13:36:39.6418575Z FAILED tests/test_initrd.py::test_initrd - subprocess.CalledProcessError: Com...
2024-01-11T13:36:39.6419624Z FAILED tests/test_initrd.py::test_initrd_luks - subprocess.CalledProcessError...
2024-01-11T13:36:39.6420394Z ========== 3 failed, 13 passed, 254 deselected in 1456.05s (0:24:16) ===========

**Comment by behrmann** [comment]
About the grub commit: I'm not sure whether other people than our CI do this, but grub tends to be heavily patched by each distro, so grub from the tools tree might not at all behave like in the target distro.

**Comment by DaanDeMeyer** [comment]
That's true but I'm hoping they primarily patch the modules and not the tools. But let's see.

**Pull request merged**
