### PR TITLE
debian: Add --force-architecture to dpkg options

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
This fixes builds for foreign architectures

### CODE REVIEW

**Comment by behrmann** [comment]
Could we gate the `--force-architecture` and `--force-depends` to only builds where the target architecture is not the same as the host architecture?

**Review by bluca — APPROVED** [review]
fixes my issue, thanks

**Comment by DaanDeMeyer** [comment]
> Could we gate the --force-architecture and --force-depends to only builds where the target architecture is not the same as the host architecture?

I think these are mostly harmless? --force-depends only does something if dpkg can't figure it out on its own and I think we prefer having dpkg try something in that case rather than hard failing

**Comment by behrmann** [comment]
> I think these are mostly harmless? --force-depends only does something if dpkg can't figure it out on its own and I think we prefer having dpkg try something in that case rather than hard failing

I'm not entirely sure that downgrading all dependency problems to warnings is desirable and I'm also not entirely sure about ignoring all architecture constraints, but we can run with it and see whether anybody reports a bug.

**Pull request merged**
