### PR TITLE
Detect Azure Linux properly

### LINKED ISSUE #2988: error detecting Azure Linux host (`os-release`'s `"azurelinux"` != `mkosi`'s `"azure"`)
### mkosi commit the issue has been seen with

main

### Used host distribution

Azure Linux 3.0

### Used target distribution

Azure Linux 3.0

### Linux kernel version used

kernel-6.6.47.1-1.azl3

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

`mkosi` knows about Azure Linux 3.0 now, thanks to #2833 🎉, but uses `azure` as the moniker instead of the `azurelinux` moniker that Azure Linux 3.0+ uses in `os-release`, e.g.:

```
NAME="Microsoft Azure Linux"
VERSION="3.0.20240824"
ID=azurelinux
VERSION_ID="3.0"
PRETTY_NAME="Microsoft Azure Linux 3.0"
```

This appears to result in the host not being correctly detected, and then things start failing thereafter (see error output below).

A naive `s/azure/azurelinux/g` in `mkosi` gets past this issue (well, at least far enough to hit a different one 🙂 ). I'm happy to submit a PR but wanted to check in with y'all first as to how you'd envision resolving this. (Would you instead prefer to keep the distribution enum and conf-file value as-is and instead add an indirection/alias?)

### Used mkosi config

_No response_

### mkosi output

```sh
‣ Distribution of your host can't be detected or isn't a supported target. Defaulting to Distribution=custom.
‣ Distribution of your host can't be detected or isn't a supported target. Defaulting to Distribution=custom.
‣ Syncing package manager metadata for default image
‣ Building default image
‣  Installing Custom
Traceback (most recent call last):
  File "/home/reubeno/mkosi/mkosi/run.py", line 63, in uncaught_exception_handler
    yield
  File "/home/reubeno/mkosi/mkosi/run.py", line 104, in fork_and_wait
    target(*args, **kwargs)
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 4676, in run_build
    build_image(
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 3906, in build_image
    install_distribution(context)
  File "/home/reubeno/mkosi/mkosi/__init__.py", line 174, in install_distribution
    (context.root / "etc/machine-id").write_text("uninitialized\n")
  File "/usr/lib/python3.12/pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/reubeno/.cache/mkosi/mkosi-workspace-_7wu37qc/root/etc/machine-id'
```

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Fixes #2988

### CODE REVIEW

**Comment by reubeno** [comment]
Thanks for the quick turnaround! I tried your change and confirmed that it resolved the issue I was running into. I can now successfully run `mkosi -t disk` without any other custom conf and get an image.

(I can't yet do the same within my cloned copy of this repo, but that's because `mkosi/resources/mkosi-tools/mkosi.conf.d/10-azure.conf` references `erofs-utils`, which doesn't presently exist in Azure Linux. Removing that unblocks the latter. Should I file a separate issue/PR for that?)

**Comment by DaanDeMeyer** [comment]
@reubeno `erofs-utils` was there last week. Can you figure out why it was removed?

**Comment by reubeno** [comment]
@DaanDeMeyer https://github.com/microsoft/azurelinux/pull/9971 added EROFS support in the Azure Linux 3.0 kernel, but I can't see any indication that the userspace tools (i.e., `erofs-utils`) were ever present.

With that said, they seem like they ought to be in the distro too now that kernel support has been enabled. FYI to @christopherco

**Comment by hsiangkao** [comment]
> @DaanDeMeyer [microsoft/azurelinux#9971](https://github.com/microsoft/azurelinux/pull/9971) added EROFS support in the Azure Linux 3.0 kernel, but I can't see any indication that the userspace tools (i.e., `erofs-utils`) were ever present.
> 
> With that said, they seem like they ought to be in the distro too now that kernel support has been enabled. FYI to @christopherco

JFYI: we're now at erofs-utils 1.8.1, yet recently there are some new hotfixes submited.
I think I will release erofs-utils 1.8.2 this weekend.

**Comment by DaanDeMeyer** [comment]
> @DaanDeMeyer [microsoft/azurelinux#9971](https://github.com/microsoft/azurelinux/pull/9971) added EROFS support in the Azure Linux 3.0 kernel, but I can't see any indication that the userspace tools (i.e., `erofs-utils`) were ever present.
> 
> With that said, they seem like they ought to be in the distro too now that kernel support has been enabled. FYI to @christopherco

It was actually a bug in mkosi uncovered by this fix, so it indeed never was available in azure linux.

**Comment by reubeno** [comment]
Thanks for the quick turnaround and resolution! I really appreciate the effort you've put into supporting Azure Linux.

**Comment by hsiangkao** [comment]
> > @DaanDeMeyer [microsoft/azurelinux#9971](https://github.com/microsoft/azurelinux/pull/9971) added EROFS support in the Azure Linux 3.0 kernel, but I can't see any indication that the userspace tools (i.e., `erofs-utils`) were ever present.
> > With that said, they seem like they ought to be in the distro too now that kernel support has been enabled. FYI to @christopherco
> 
> JFYI: we're now at erofs-utils 1.8.1, yet recently there are some new hotfixes submited. I think I will release erofs-utils 1.8.2 this weekend.

Hi @christopherco, in case that erofs-utils may be interesting, I've released erofs-utils 1.8.2 yesterday.
and the current use cases (maybe incomplete) are documented on the website too: https://erofs.docs.kernel.org

**Pull request merged**
