### PR TITLE
Use black for code formatting

### PR DESCRIPTION
**Pull request by behrmann**
This is a big one and [black](https://github.com/psf/black) is not PEP8-compliant (not like we were before with the line length of 119), but it's being used more and more from what I see. The nice thing is, that it has almost *no* configuration. There is no discussion about style. It comes in any colour you want, as long as it's black. :)

The three commits in this PR: configure black, run black on all relevant files, and add it to our CI.

### CODE REVIEW

**Comment by behrmann** [comment]
Ah, the mere existence of pyproject.toml breaks the editable user install.

**Comment by behrmann** [comment]
The latest commit is a bit on the nose. I wanted to see, whether this works as a workaround. I guess I'll need to look into how to get us into the glorious pyproject.toml future.

**Comment by DaanDeMeyer** [comment]
There should be a --no-pep-517 flag we can pass to tell pip not to use pyproject.toml. We can just add that to the instructions for the editable install no? Pep 517 doesn't support editable installs it seems.

**Comment by DaanDeMeyer** [comment]
Should we use [this](https://github.com/psf/black#github-actions) for CI?

**Comment by behrmann** [comment]
> There should be a --no-pep-517 flag we can pass to tell pip not to use pyproject.toml. We can just add that to the instructions for the editable install no? Pep 517 doesn't support editable installs it seems.

Yes, there is `--no-use-pep517`, but I had hoped there was something else than having people need to type that when using editable install, but it seems that's it for now. I added it to the README, hopefully nobody will stumble too hard over this. I'm always hesitant to change the installation workflow.

> Should we use [this](https://github.com/psf/black#github-actions) for CI?

I saw this as well, but I don't think it's really worth it to pull this in and have spin up another test runner, if we can add two lines to ours to do roughly the same.

**Comment by DaanDeMeyer** [comment]
> Yes, there is --no-use-pep517, but I had hoped there was something else than having people need to type that when using editable install, but it seems that's it for now. I added it to the README, hopefully nobody will stumble too hard over this. I'm always hesitant to change the installation workflow.

This is fine, ti's a one time setup anyway. I've executed it once and never looked at it again. (Somewhat related, thank you for pushing so much for pip when I was pushing for zipapp. the editable install turns out to be extremely useful in practice, I can't live without it anymore).

**Comment by behrmann** [comment]
> [..] (Somewhat related, thank you for pushing so much for pip when I was pushing for zipapp. the editable install turns out to be extremely useful in practice, I can't live without it anymore).

Glad this worked out. :)

**Pull request merged**
