### PR TITLE
mkosi: Fix centos_epel mirror configuration

### PR DESCRIPTION
**Pull request by stejoo**
Fix the mirrors for the `centos_epel` _distribution_.
Related: https://github.com/systemd/mkosi/pull/346

### CODE REVIEW

**Comment by stejoo** [comment]
In short: `centos_epel` distribution could use broken mirror configuration when falling back on the defaults. I altered the mirrorlist URL for the centosplus repository and changed the mirrorlist for EPEL to a baseurl, because that's what it should be.
Works for me now when building a non-bootable image using:
```
$ sudo mkosi --distribution centos --format raw_gpt --output centos.img --password ohmypassphrase
```

**Comment by poettering** [comment]
hmm @sequencer any chance you can comment on this?

**Comment by sequencer** [comment]
I’ll check this tonight. Sorry for the delay.

**Comment by sequencer** [comment]
I just checked the upstream config, @stejoo is right.
These are my fault, sorry for the bug I introduced.

**Pull request merged**
