### PR TITLE
Fix repart definition for ESP builds

### PR DESCRIPTION
**Pull request by septatrix**
Currently ESP builds succeed but do not actually include any UKI as sd-repart silently ignore that they are missing. I am not sure if this is the correct place to add that fix. Maybe a `--copy-from` in the repart invocation would be cleaner.

Also, disk builds with UKI bootloaders are still broken - not sure if anything else is affected, too

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]
Yikes, good catch

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
We also need to pass something like `--ro-bind, uki, workdir(uki)` to the sandbox options of `make_image()`

**Comment by septatrix** [comment]
> We also need to pass something like `--ro-bind, uki, workdir(uki)` to the sandbox options of `make_image()`

Do we? The uki is implicitly mounted as part of the staging dir under `/work`. Or do you suggest that as an alternative to adjusting the repart definition?

I am really not sure where the best place to put this fix is.

**Comment by septatrix** [comment]
And I took a look at the logs when building a disk image with a UKI as a bootloader but was unable to find the error in that case...

**Comment by DaanDeMeyer** [comment]
> > We also need to pass something like `--ro-bind, uki, workdir(uki)` to the sandbox options of `make_image()`
> 
> Do we? The uki is implicitly mounted as part of the staging dir under `/work`. Or do you suggest that as an alternative to adjusting the repart definition?
> 
> I am really not sure where the best place to put this fix is.

You are correct that it's available in the sandbox, it's the "implicit" that's the problem. We mount in the staging directory for another unrelated reason and that might change in the future so I'd like to make it explicit. Just adding an `options` argument to `make_image()` and then passing it through is good enough.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
