### PR TITLE
Add options to run scripts with network access

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
(Note: this PR is based on #64.)

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Note: this was intended as a fix to systemd/systemd#5324, but apparently doesn’t fix that issue – I still get the error even without `--private-network` – so I should probably investigate that some more before this is merged.

**Comment by keszybz** [comment]
If it works correctly, this should be merged anyway. It useful functionality, even if it doesn't fix your issue. Do you plan to amend this patch, or is it OK as is?

**Comment by poettering** [comment]
hmm, do we we really need the ability to switch on networking for postinst and build independently? I'd prefer if we could keep the exposed settings minimal, hence a single boolean enabling it in both is a lot more attractive to me...

**Comment by keszybz** [comment]
Right, a single `--with-network` that applies to the whole build...

**Comment by lucaswerkmeister** [comment]
Well, I thought requiring network access in `postinst` would probably be even rarer than in `build`, so `--build-with-network` ought to be enough for most projects… but I can rework this to a single `--with-network` too, sure.

**Comment by lucaswerkmeister** [comment]
Alright, new version pushed. Here’s a simple `mkosi.build` script to test the change, by the way:
```bash
#!/bin/bash

exec 3<>/dev/udp/8.8.8.8/53
```
`sudo mkosi` should fail, `sudo mkosi --with-network` shouldn’t.

**Pull request merged**
