### PR TITLE
qemu: Add if=virtio option.

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Speeds up boot from 12s to 6s.

### CODE REVIEW

**Comment by behrmann** [comment]
I guess it's worth to try this out. Starting qemu directly might not affect too many people and if it makes problems it can always be hidden behind a switch.

**Comment by DaanDeMeyer** [comment]
I certainly hope no one's using `mkosi qemu` to run production QEMU VMs. This does require a few drivers on the guest image to be installed though so I'm going to do a quick check for ubuntu, debian, fedora and centos to make sure those drivers are available there.

**Comment by DaanDeMeyer** [comment]
These all boot fine for me so I'm guessing we're good. I think the dracut qemu module pulls in the necessary drivers.

**Comment by behrmann** [comment]
Indeed. For later reference qemu pulls in the following modules at the moment via `90qemu`
- ata_piix ata_generic 
- pata_acpi cdrom 
- sr_mod ahci 
- virtio_blk 
- virtio virtio_ring 
- virtio_pci 
- virtio_scsi virtio_console 
- virtio_rng 
- spapr-vscsi 
- qemu_fw_cfg
and 
- virtio_net 
- e1000 
- 8139cp 
- pcnet32 
- e100 
- ne2k_pci
via `90qemu-net`. 

I think we should be on the safe side with this already, but if somethings missing we can add it if bug reports come rolling in.

**Pull request merged**
