### PR TITLE
Modernization of string formatting syntax and set construction

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
```
/home/runner/work/mkosi/mkosi/mkosi/__init__.py
  /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3170:86 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "maps" of type "MutableMapping[_KT@ChainMap, _VT@ChainMap]" in function "__init__"
    TypeVar "_VT@MutableMapping" is invariant
      Type "Path | str" cannot be assigned to type "str" (reportGeneralTypeIssues)
  /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3170:91 - error: Argument of type "_Environ[str]" cannot be assigned to parameter "maps" of type "MutableMapping[_KT@ChainMap, _VT@ChainMap]" in function "__init__"
    TypeVar "_VT@MutableMapping" is invariant
      Type "Path | str" cannot be assigned to type "str" (reportGeneralTypeIssues)
  /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3916:58 - error: No overloads for "join" match the provided arguments
    Argument types: (DirEntry[TypeVar], Literal['modules.dep']) (reportGeneralTypeIssues)
3 errors, 0 warnings, 0 infos 
```

Pyright is unhappy, but I didn't touch those lines in this PR.

**Review by behrmann — APPROVED** [review]
LGTM. I'm very happy we can finally use `text=` instead of `universal_newlines=` :)

**Comment by behrmann** [comment]
> ```
> /home/runner/work/mkosi/mkosi/mkosi/__init__.py
>   /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3170:86 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "maps" of type "MutableMapping[_KT@ChainMap, _VT@ChainMap]" in function "__init__"
>     TypeVar "_VT@MutableMapping" is invariant
>       Type "Path | str" cannot be assigned to type "str" (reportGeneralTypeIssues)
>   /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3170:91 - error: Argument of type "_Environ[str]" cannot be assigned to parameter "maps" of type "MutableMapping[_KT@ChainMap, _VT@ChainMap]" in function "__init__"
>     TypeVar "_VT@MutableMapping" is invariant
>       Type "Path | str" cannot be assigned to type "str" (reportGeneralTypeIssues)
>   /home/runner/work/mkosi/mkosi/mkosi/__init__.py:3916:58 - error: No overloads for "join" match the provided arguments
>     Argument types: (DirEntry[TypeVar], Literal['modules.dep']) (reportGeneralTypeIssues)
> 3 errors, 0 warnings, 0 infos 
> ```
> 
> Pyright is unhappy, but I didn't touch those lines in this PR.

On my local machine I'm still running pyright `1.1.171`, but I saw that upstream is at `1.1.174`, so I guess we're pulling that in now. Maybe we can pin that to `1.1.171` for now.

**Comment by behrmann** [comment]
The error on line 3170 looks somewhat valid, it's about on calling `str()` on `root` and the return value of `output_dir`. 

The error on 3916 looks spurious to me, it doesn't know that `os.path.join` can take a `DirEntry`, which it probably can thanks to ducktyping. One could change
```diff
- os.path.isfile(os.path.join(kver, "modules.dep"))
+ Path(kver.path).joinpath("modules.dep").is_file()
```
or 
```diff
- os.path.isfile(os.path.join(kver, "modules.dep"))
+ (Path(kver.path) / "modules.dep").is_file()
```
though, to both make it more readable and appease pyright. (Haven't checked that it does, just assuming, that it would).

**Comment by keszybz** [comment]
Doesn't seem to help.

**Comment by behrmann** [comment]
Unfortunate, I just checked, the other issue goes away with explicit calls to `str()`, but the thing around `kver` seems like a bug to me. It can be silenced by adding a `cast(str, <>)` around `kver`, so that and a comment, that it's a temporary workaround for a pyright bug might be the prudent solution.

**Comment by keszybz** [comment]
Arrgh, `# type:ignore` silences pyright, but makes mypy complain about unused comments. I'm starting to wonder if the effort to support pyright is worth it.

**Comment by keszybz** [comment]
I'll this as is. Pyright failures are not related to this PR, so let's consider them separately.

**Comment by behrmann** [comment]
Yes, stumbled about that already, that's why I proposed the `cast` :) We can probably also just delete the `warn_unused_ignores` from `setup.cfg`, there's only two ignores left in mkosi.

**Comment by keszybz** [comment]
Rebased on top of #822.

**Comment by keszybz** [comment]
CI fail is unrelated:
```
Error: Failed to download metadata for repo 'epel': Yum repo downloading error: Downloading error(s): repodata/e793ab711de6675dbaff69b5ac3b3691f5b365cee7ffc47ccb4e6b2b4be5ec83-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/38a90c7bcee036e639093c8b7ce8b8f9d8e884c881aa815748f62796b7acd53f-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/057c561e9daac4799b51ce128eadbc94911e66afd562c8b2ee30bef5856138a8-prestodelta.xml.xz - Cannot download, all mirrors were already tried without success; repodata/876acf7abba43b3a5b635d7092b7026d82650402dba8c7aea7606091df6d037e-updateinfo.xml.bz2 - Cannot download, all mirrors were already tried without success
```

**Comment by behrmann** [comment]
> CI fail is unrelated:
> 

Yep, let's merge this.

**Pull request merged**
