### PR TITLE
ci: Only run CI workflow if the unit tests workflow succeeded

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by behrmann** [comment]
Great change! Let's see whether it works as advertised. :)

**Comment by behrmann** [comment]
Looks like the rest is missing?

**Comment by DaanDeMeyer** [comment]
Trying some different syntax, from what I can understand from the docs, this should work

**Comment by DaanDeMeyer** [comment]
That didn't work either, trying a different approach.

**Comment by DaanDeMeyer** [comment]
Seems it works with this approach

image

**Comment by DaanDeMeyer** [comment]
Let's merge since this works

**Pull request merged**
