### PR TITLE
Add logging to qemu_check_kvm_support()

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by bluca** [comment]
```
$ sudo bin/mkosi -d debian qemu
‣ Permission denied to access /dev/kvm. Not using KVM acceleration
```

is it using a mount namespace or something?

**Comment by DaanDeMeyer** [comment]
> is it using a mount namespace or something?

It is, but that's not the issue. We run qemu unprivileged when invoked with sudo, that's the issue because on debian unprivileged users can't use /dev/kvm.

**Review by bluca — APPROVED** [review]
I see, the additional logging added looks fine to have tho

**Comment by DaanDeMeyer** [comment]
@bluca Try again, I added a commit to not change to the invoking user if we're invoked as root and running qemu.

**Comment by bluca** [comment]
Still perm denied:

```
$ sudo bin/mkosi -d debian qemu
‣ Permission denied to access /dev/kvm. Not using KVM acceleration
```

**Comment by DaanDeMeyer** [comment]
Euhh might have been a stupid operator precedence issue, try again?

**Comment by bluca** [comment]
computer says no, same result

**Comment by DaanDeMeyer** [comment]
Fuck this conditional is messing with my brain, try again, third time's the charm

**Review by bluca — APPROVED** [review]
and it was! Ship it!

**Review by behrmann — APPROVED** [review]

**Pull request merged**
