### PR TITLE
Loop device fixes

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by behrmann** [comment]
Changes look fine to me in principle. I had hoped it would fix the current CI failures.

**Comment by DaanDeMeyer** [comment]
I'm not sure, it's failing in BIOS now, it used to fail much earlier I think

**Comment by DaanDeMeyer** [comment]
@bluca Can you check this PR in OBS, I'm specifically curious if we'll still get the -EINVAL

**Comment by bluca** [comment]
Ran a few builds, with btrfs/ext4 and verity, no issues, ship it!

**Comment by bluca** [comment]
Ah spoke too soon:

```
[  122s] The partition table has been altered.
[  122s] Traceback (most recent call last):
[  122s]   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[  122s]     return _run_code(code, main_globals, None,
[  122s]   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[  122s]     exec(code, run_globals)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__main__.py", line 36, in <module>
[  122s]     main()
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__main__.py", line 27, in main
[  122s]     run_verb(a)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__init__.py", line 8248, in run_verb
[  122s]     manifest = build_stuff(args)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__init__.py", line 7588, in build_stuff
[  122s]     image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__init__.py", line 7346, in build_image
[  122s]     generated_root_part = insert_generated_root(args, raw, loopdev, generated_root, for_cache)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__init__.py", line 3817, in insert_generated_root
[  122s]     return insert_partition(
[  122s]   File "/usr/src/packages/SOURCES/mkosi/__init__.py", line 3779, in insert_partition
[  122s]     args.partition_table.run_sfdisk(loopdev)
[  122s]   File "/usr/src/packages/SOURCES/mkosi/backend.py", line 440, in run_sfdisk
[  122s]     block_reread_partition_table(f.fileno())
[  122s]   File "/usr/src/packages/SOURCES/mkosi/syscall.py", line 92, in block_reread_partition_table
[  122s]     fcntl.ioctl(fd, BLKRRPART, 0)
[  122s] OSError: [Errno 22] Invalid argument
```

**Comment by DaanDeMeyer** [comment]
@bluca Can you try again and post the logs again? I added some extra logging that might help to figure out what's going wrong

**Comment by bluca** [comment]
Sure, will trade that for a review of https://github.com/systemd/mkosi/pull/1132 :-P
Might take some time, if you don't see an answer by lunch time it will be late tonight

**Comment by bluca** [comment]
I could only reproduce it with an Arch build, and unfortunately Arch is borken today (must be a day ending in `y` again!), for reasons completely unrelated to mkosi. I will try again tonight and tomorrow.

**Comment by bluca** [comment]
Building Fedora 36:

```
[   95s] ‣   Extracting partition…
[  101s] 6291456+0 records in
[  101s] 6291456+0 records out
[  101s] 3221225472 bytes (3.2 GB, 3.0 GiB) copied, 5.7816 s, 557 MB/s
[  101s] ‣   Generating verity hashes…
[  101s] 6291456+0 records in
[  101s] 6291456+0 records out
[  101s] 3221225472 bytes (3.2 GB, 3.0 GiB) copied, 5.7816 s, 557 MB/s
[  101s] ‣   Generating verity hashes…
[  112s] ‣   Inserting verity partition…
[  112s] ‣    Resizing disk image to 3.0G
[  112s] ‣    Inserting partition of 24.2M...
[  112s] GPT PMBR size mismatch (6291535 != 6341087) will be corrected by write.
[  112s] The backup GPT table is not on the end of the device. This problem will be corrected by write.
[  112s] Disk /dev/loop0: 3.02 GiB, 3246637056 bytes, 6341088 sectors
[  112s] Units: sectors of 1 * 512 = 512 bytes
[  112s] Sector size (logical/physical): 512 bytes / 512 bytes
[  112s] I/O size (minimum/optimal): 512 bytes / 512 bytes
[  112s] Disklabel type: gpt
[  112s] Disk identifier: E7B325CA-88DC-3841-8EFF-4D8329F51B37
[  112s] 
[  112s] Old situation:
[  112s] 
[  112s] Device       Start     End Sectors Size Type
[  112s] /dev/loop0p1    40 6291495 6291456   3G Linux root (x86-64)
[  112s] 
[  112s] >>> Script header accepted.
[  112s] >>> Script header accepted.
[  112s] >>> Script header accepted.
[  112s] >>> Created a new GPT disklabel (GUID: 998D82EF-0059-3143-986F-3DAB1A3C8515).
[  112s] /dev/loop0p1: Created a new partition 1 of type 'Linux root (x86-64)' and of size 3 GiB.
[  112s] Partition #1 contains a ext4 signature.
[  112s] /dev/loop0p2: Created a new partition 2 of type 'Linux root verity (x86-64)' and of size 24.2 MiB.
[  112s] /dev/loop0p3: Done.
[  112s] 
[  112s] New situation:
[  112s] Disklabel type: gpt
[  112s] Disk identifier: 998D82EF-0059-3143-986F-3DAB1A3C8515
[  112s] 
[  112s] Device         Start     End Sectors  Size Type
[  112s] /dev/loop0p1      40 6291495 6291456    3G Linux root (x86-64)
[  112s] /dev/loop0p2 6291496 6341047   49552 24.2M Linux root verity (x86-64)
[  112s] 
[  112s] The partition table has been altered.
[  112s] ‣ Error: Failed to reread partition table of /dev/loop0: Invalid argument
[  113s] Root partition-type UUID: 36311f8b-51ce-9fb0-dabc-9a2e56feee2c
[  113s] ### VM INTERACTION START ###
```

**Comment by DaanDeMeyer** [comment]
No clue, I can't reproduce locally, I've made EINVAL non-fatal, should be sufficient for now.

**Comment by bluca** [comment]
Will give it a run shortly

**Comment by bluca** [comment]
Ship it!

```
[  225s] >>> Created a new GPT disklabel (GUID: 830C1BF7-BA69-2E4B-BD38-02E11EBBDADA).
[  225s] /dev/loop0p1: Created a new partition 1 of type 'EFI System' and of size 256 MiB.
[  225s] Partition #1 contains a vfat signature.
[  225s] /dev/loop0p2: Created a new partition 2 of type 'Linux root (x86-64)' and of size 3 GiB.
[  225s] Partition #2 contains a btrfs signature.
[  225s] /dev/loop0p3: Created a new partition 3 of type 'Linux root verity (x86-64)' and of size 24.2 MiB.
[  225s] /dev/loop0p4: Done.
[  225s] 
[  225s] New situation:
[  225s] Disklabel type: gpt
[  225s] Disk identifier: 830C1BF7-BA69-2E4B-BD38-02E11EBBDADA
[  225s] 
[  225s] Device         Start     End Sectors  Size Type
[  225s] /dev/loop0p1      40  524327  524288  256M EFI System
[  225s] /dev/loop0p2  524328 6815783 6291456    3G Linux root (x86-64)
[  225s] /dev/loop0p3 6815784 6865335   49552 24.2M Linux root verity (x86-64)
[  225s] 
[  225s] The partition table has been altered.
[  225s] ‣ Warning: Failed to reread partition table of /dev/loop0: Invalid argument
[  225s] ‣    Writing partition...
[  225s] ‣   Mounting image…
[  225s] ‣    Generating combined kernel + initrd boot file…
[  226s] ‣   Unmounting image…
[  226s] ‣   Mounting image…
[  226s] ‣   Unmounting image…
[  226s] ‣  Detaching /dev/loop0
[  226s] ‣ Digging holes into output file /usr/src/packages/OTHER/fedora~36/.mkosi-fnj2q2dk…
[  227s] ‣ Digging holes into output file /usr/src/packages/OTHER/fedora~36/.mkosi-24d_8_8h…
[  227s] ‣ Digging holes into output file /usr/src/packages/OTHER/fedora~36/.mkosi-icx91yxs…
[  227s] ‣ Digging holes into output file /usr/src/packages/OTHER/fedora~36/.mkosi-41rcs66q…
[  227s] ‣ Writing .root.roothash file…
```

**Review by bluca — APPROVED** [review]

**Review by behrmann — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
Failures are all in BIOS, which will be fixed when we drop BIOS support in the other PR

**Pull request merged**
