### PR TITLE
Rpm from source

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Possible fix for fedora issue in https://github.com/systemd/systemd/pull/17787

### CODE REVIEW

**Comment by behrmann** [comment]
This still misses the lua headers if `--with-lua` is necessary.

**Comment by behrmann** [comment]
RPM says in their INSTALL file that having the lua scripting support is recommended, so installing liblua5.2-dev seems sensible.

**Comment by DaanDeMeyer** [comment]
You're right, the CI was failing due to missing lua stuff in rpm. The errors are very similar to the ones I'm trying to fix in systemd so I'm pretty confident this will fix that issue as well.

**Comment by behrmann** [comment]
The opensuse tar build is an interesting false positive, as it doesn't seem to build anything.

**Comment by DaanDeMeyer** [comment]
I think we need to build libzypp and zypper from source now as well

**Comment by DaanDeMeyer** [comment]
Nvm, decided to drop opensuse, mageia, openmandriva, clear and photon support from CI. The overhead is just too big while we don't even know if anyone is using these with mkosi. Let's stick to the popular distros and save ourselves the hassle.

Will split everything up into proper commits tomorrow.

**Comment by behrmann** [comment]
Agreed, although the opensuse stuff might be worthwhile, since it's advertised on the packaging (the README talks about being mkosi being a fancy wrapper around zypper as well) and opensuse is somewhat popular in university/research settings and finance, if I remember correctly.

**Comment by DaanDeMeyer** [comment]
I can't be bothered getting libzypp/zypper to build from source on Ubuntu. I've never worked with CMake builds as bad as those (I have to install nginx to build a package manager). If someone is interested in using mkosi's opensuse support and wants to make sure CI is running for mkosi, they should step up and help us out. If I have to deal any more with package manager build issues I'll lose my sanity and no work will get done at all on mkosi.

**Comment by DaanDeMeyer** [comment]
Split into two commits.

**Review by behrmann — APPROVED** [review]

**Comment by behrmann** [comment]
LGTM

**Comment by DaanDeMeyer** [comment]
I'm going to do one more release with this fix in as well. Bit of release spam doesn't hurt anyone I guess.

**Pull request merged**
