### PR TITLE
Add PowerTools repo for CentOS Stream 8

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Enables installing development related packages (e.g. meson).

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
centos tests failing is expected because of https://github.com/systemd/mkosi/pull/915#issuecomment-1049035316

**Review by bluca — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
Doesn't affect gentoo so merging

**Comment by davide125** [comment]
Ah, good catch! We should also add CRB (the equivalent of PowerTools) for CentOS Stream 9.

**Comment by DaanDeMeyer** [comment]
I checked and it seems you added that one already

**Comment by davide125** [comment]
Yup, I just realized: https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L2466 so we're good there.

**Pull request merged**
