### PR TITLE
Use `--merged-usr` for `debootstrap` to fix #74

### LINKED ISSUE #74: `mkosi -d debian -t directory -o debian-jessie-base` fails due to "debootstrap" issue
Trying to create a Debian filesystem image using:
```
mkosi -d debian -t directory -o debian-jessie-base
```

It ends up failing like this:
```
I: Extracting liblzma5...
I: Extracting zlib1g...
W: Failure trying to run: chroot /var/tmp/machines/.mkosi-rpqjha2m/root dpkg-deb -f /var/cache/apt/archives/dpkg_1.18.23_amd64.deb Version
W: See /var/tmp/machines/.mkosi-rpqjha2m/root/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot /var/tmp/machines/.mkosi-rpqjha2m/root mount -t proc proc /proc
W: See /var/tmp/machines/.mkosi-rpqjha2m/root/debootstrap/debootstrap.log for details
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
Traceback (most recent call last):
  File "/root/mkosi/mkosi", line 2533, in <module>
    main()
  File "/root/mkosi/mkosi", line 2529, in main
    build_stuff(args)
  File "/root/mkosi/mkosi", line 2481, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/root/mkosi/mkosi", line 2379, in build_image
    install_distribution(args, workspace.name, run_build_script)
  File "/root/mkosi/mkosi", line 1012, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib64/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/root/mkosi/mkosi", line 832, in install_debian
    install_debian_or_ubuntu(args, workspace, run_build_script, args.mirror)
  File "/root/mkosi/mkosi", line 777, in install_debian_or_ubuntu
    subprocess.run(cmdline, check=True)
  File "/usr/lib64/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', 'unstable', '/var/tmp/machines/.mkosi-rpqjha2m/root', 'http://httpredir.debian.org/debian']' returned non-zero exit status 1
```

Running it manually and then inspecting the log shows this:
```
--2017-03-25 00:46:05--  http://httpredir.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.8.dfsg-5_amd64.deb
Resolving httpredir.debian.org (httpredir.debian.org)... 140.211.166.202, 149.20.4.15, 5.153.231.4, ...
Connecting to httpredir.debian.org (httpredir.debian.org)|140.211.166.202|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cdn-fastly.deb.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.8.dfsg-5_amd64.deb [following]
--2017-03-25 00:46:06--  http://cdn-fastly.deb.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.8.dfsg-5_amd64.deb
Resolving cdn-fastly.deb.debian.org (cdn-fastly.deb.debian.org)... 151.101.12.204, 2a04:4e42:3::204
Connecting to cdn-fastly.deb.debian.org (cdn-fastly.deb.debian.org)|151.101.12.204|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87522 (85K) [application/x-debian-package]
Saving to: ‘/var/tmp/machines/.mkosi-rpqjha2m/root//var/cache/apt/archives/partial/zlib1g_1%3a1.2.8.dfsg-5_amd64.deb’

     0K .......... .......... .......... .......... .......... 58% 4.16M 0s
    50K .......... .......... .......... .....                100% 20.0M=0.01s

2017-03-25 00:46:06 (6.20 MB/s) - ‘/var/tmp/machines/.mkosi-rpqjha2m/root//var/cache/apt/archives/partial/zlib1g_1%3a1.2.8.dfsg-5_amd64.deb’ saved [87522/87522]

dpkg-deb (subprocess): unable to execute tar (tar): No such file or directory
dpkg-deb: error: subprocess tar returned error exit status 2
chroot: failed to run command ‘mount’: No such file or directory
```

Running `debootstrap` manually a 2nd time succeds, so this seems to be some kind of weird issue where `$PATH` isn't re-hashed during an update and doesn't find `tar` or so, but I can't really make any sense of it… I'm not even sure whether this is purely an upstream issue or related to the way `mkosi` runs `debootstrap`.

OS: Fedora 25
mkosi git master @ d5ad357d9

### PR DESCRIPTION
**Pull request by eliasp**

### CODE REVIEW

**Comment by fsateler** [comment]
This should go away at some point in the near future when --merged-usr is the default. Note that it is no longer possible to create jessie images with this option set.

**Comment by lucaswerkmeister** [comment]
> Note that it is no longer possible to create jessie images with this option set.

Wait, that’s certainly not acceptable – but it’s working for me. What error do you get? (I ran `mkosi -d debian -r jessie`, with `mkosi` from Git, and got an image that was bootable.)

**Comment by fsateler** [comment]
>> Note that it is no longer possible to create jessie images with this option set.
>
> Wait, that’s certainly not acceptable – but it’s working for me. What error do you get? (I ran mkosi -d debian -r jessie, with mkosi from Git, and got an image that was bootable.)

Sorry for the noise. Turns out debootstrap is smart enough to know jessie doesn't support merged-usr and [ignores the option](https://sources.debian.net/src/debootstrap/1.0.89/scripts/sid/#L45).

**Comment by poettering** [comment]
Ah, I wasn't aware of the option. Yes, this should be always on indeed. Patch looks good.

**Pull request merged**
