### PR TITLE
Use https for openSUSE repo urls

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@lucaswerkmeister To be honest, I don't know. The HTTPS repos seem to work now, but you are right it could be a problem in the future.

**Comment by keszybz** [comment]
With Let's Encrypt, it's hard not to be able to afford a certificate.

**Comment by lucaswerkmeister** [comment]
Sure, but currently they’re on DigiCert, which afaik is not free.

**Comment by keszybz** [comment]
Right, but you can switch at any time. And in this day and age, HTTPS is the norm. I'm pretty sure we should change all http to https wherever supported. And where unsupported, we should ask for it to be supported.

**Pull request merged**
