### PR TITLE
unmount dev first. fix #107

### LINKED ISSUE #107: ctrl-c while donwloading packages destroys /dev/loop* on the host
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 linux-api-headers-4.10.1-1-x86_64                                            852.4 KiB  64.9K/s 00:13 [############################################################] 100%
 tzdata-2017b-1-any                                                           235.8 KiB  44.3K/s 00:05 [############################################################] 100%
 iana-etc-20170512-1-any                                                      360.9 KiB  47.5K/s 00:08 [############################################################] 100%
 filesystem-2017.03-2-x86_64                                                   10.2 KiB  16.7K/s 00:01 [############################################################] 100%
^C‣ Unmounting Package Cache...                                               540.7 KiB   199K/s 00:40 [###---------------------------------------------------------]   6%

Interrupt signal received

‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
‣ Detaching image file...
‣ Detaching image file complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 2764, in <module>
    main()
  File "/usr/bin/mkosi", line 2760, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 2712, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 2567, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1090, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 988, in install_arch
    subprocess.run(cmdline, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 828, in communicate
    self.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'hugepages'
```
the host lost all of the `/dev/loop*` device nodes
```
$ ls -l /dev/loop-control
ls: cannot access '/dev/loop-control': No such file or directory
$ sudo rmmod loop
$ sudo modprobe loop
$ ls -l /dev/loop-control
crw-rw---- 1 root disk 10, 237 Jun 30 22:53 /dev/loop-control
```

### PR DESCRIPTION
**Pull request by gdamjan**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, can you elaborate what precisely this changes? ideally in the commit msg!

**Comment by gdamjan** [comment]
still, ctrl-c gives this error
```
( 49/114) installing libarchive                                                                        [############################################################] 100%
( 50/114) installing findutils                                                                         [############################################################] 100%
^C51/114) installing pcre                                                                              [------------------------------------------------------------]   0%
Interrupt signal received
‣ Unmounting Package Cache...
( 51/114) installing pcre                                                                              [############################################################] 100%
‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
‣ Detaching image file...
‣ Detaching image file complete.
Traceback (most recent call last):
  File "./mkosi", line 2777, in <module>
    main()
  File "./mkosi", line 2773, in main
    build_stuff(args)
  File "./mkosi", line 2725, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "./mkosi", line 2580, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "./mkosi", line 1103, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "./mkosi", line 1001, in install_arch
    subprocess.run(cmdline, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 828, in communicate
    self.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.6/tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 30] Read-only file system: 'kexec_loaded'
```

**Comment by gdamjan** [comment]
Not sure if the change is correct (in all cases). I'll amend the commit message if the change is ok.

**Comment by poettering** [comment]
can you elaborate on the rationale? i don't grok the effect the patch is supposed to have!

**Comment by keszybz** [comment]
This has gone stale. Please submit a new PR if you want to work on this.

**Pull request closed without merging**
