### PR TITLE
Rename some opts to be more consistent

### PR DESCRIPTION
**Pull request by NekkoDroid**
Just noticed some directory long opts used `dir=` while others used `directory=`, should all now be consistently `directory=`.

### CODE REVIEW

**Review by behrmann — APPROVED** [review]
I like the longer name a bit better and changing it from `-directory` to `-dir` leaves the `--directory` option, but it's still more consistent than the status quo.

**Comment by NekkoDroid** [comment]
I am also fine with changing them all to use the longer `*-directory=`

**Comment by behrmann** [comment]
Let's have @DaanDeMeyer weigh in, since he just added another. Either way this PR will need a rebase.

**Comment by NekkoDroid** [comment]
Changed them to the longer `*-directory=`. I think I got most of them all with the exception of `--wipe-build-dir` as that (from what I see) doesn't have a way to keep backwards compat.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
