### PR TITLE
Bind mount postinst script rather than copying

### PR DESCRIPTION
**Pull request by lucasdemarchi**
@keszybz  what did you mean in the comment I just removed? Just bind-mounting the postinst script to / works for me, so I don't understand the issue.

### CODE REVIEW

**Comment by poettering** [comment]
But this leaves the /postinst file we mount over around in the container after it completed, no?

**Comment by lucasdemarchi** [comment]
it uses systemd-nspawn to mount it. systemd-nspawn doesn't leave them mounted after return. This is equivalent to how we enable `--with-network`.

**Comment by poettering** [comment]
> it uses systemd-nspawn to mount it. systemd-nspawn doesn't leave them mounted after return. This is equivalent to how we enable `--with-network`.

It doesn't leave them mounted, but it does create the file/dir to mount it over, and it doesn#t clean that up...

**Comment by poettering** [comment]
The old code did an unlink() after it completed operation. The new code doesn't do that, it binds mounts it in using the fact that nspawn will create a mount point to mount over implicitly if it's missing, but then never cleans that mount point up after use...

The comment in there is supposed to explain that: creating the file to mount over first, and then mounting it over is not too much better than copying the file in the first place, since either way a file is create that needs to be unlinked afterwards...

**Comment by lucasdemarchi** [comment]
humn... true, that. I was expecting systemd-nspawn to actually remove the file if it created it in order to bind-mount.... I missed that nspawn-mount.c doesn't undo the file/dir creation

**Pull request closed without merging**
