### PR TITLE
Install extra trees after installing build results

### LINKED ISSUE #789: RFC: Switch order of mkosi.extra/ and copying build results?
In the case of systemd, copying the build results into the final image also copies a bunch of configuration files into the final image. We currently can't override these by using mkosi.extra/. I'm unsure if there's any big advantage to the current order so I propose we switch the order so we can override installed files from the build if needed.

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Fixes #789

### CODE REVIEW

**Comment by behrmann** [comment]
I think the flow chart in the man page needs to be adjusted, no? "copy build results" moves before "copy extra trees".

**Comment by DaanDeMeyer** [comment]
Updated manual with the necessary changes. @behrmann Heads up we added you to mkosi-maintainers so you can merge PRs now as well.

**Comment by behrmann** [comment]
Yeah, got the mail. Thanks for added responsibility :)

**Comment by poettering** [comment]
makes sense to me. In particular as we have the "skeleton" trees for the early stuff already.

lgtm

**Pull request merged**
