### PR TITLE
action: bump archlinux-keyring to 20220713

### PR DESCRIPTION
**Pull request by mrc0mmand**
See: https://bugs.archlinux.org/task/75427

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Thanks! this is a lot simpler than what I'd have tried

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by mrc0mmand** [comment]
Oh well, I though this was way too simple - now pacman doesn't segfault, but still fails to import the signature:

```
 error: libcap: key "991F6E3F0765CF6295888586139B09DA5BF0D338" is unknown
:: Import PGP key 991F6E3F0765CF6295888586139B09DA5BF0D338? [Y/n] error: key "991F6E3F0765CF6295888586139B09DA5BF0D338" could not be imported

:: File /home/runner/work/mkosi/mkosi/mkosi.output/.mkosi-j2iy9772/root/var/cache/pacman/pkg/libcap-2.65-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)
```

*sigh*

**Comment by mrc0mmand** [comment]
But I have another idea, gimme a sec.

**Comment by DaanDeMeyer** [comment]
Do we need both or could bumping the keyring package version be sufficient?

**Comment by mrc0mmand** [comment]
> Do we need both or could bumping the keyring package version be sufficient?

I just tried it without the first commit locally and it seems to be working (it didn't for me when I tried it for the first time, but that's probably on me), so let me drop the workaround and see how it's going to fare.

**Comment by mrc0mmand** [comment]
Oh well, apparently it was indeed an issue on my side, so bumping the keyring version is enough.

**Comment by DaanDeMeyer** [comment]
Cool, let's do that for now.

It'd be kinda nice if pacman/archlinux-keyring got packaged in ubuntu

**Comment by DaanDeMeyer** [comment]
No need to wait for the rest

**Comment by mrc0mmand** [comment]
> Cool, let's do that for now.
> 
> It'd be kinda nice if pacman/archlinux-keyring got packaged in ubuntu

Yeah, that would make things definitely much easier.

**Pull request merged**
