### PR TITLE
Move action to repository root

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Publishing an action to the marketplace requires the action metadata
file to be in the repository root.

### CODE REVIEW

**Comment by behrmann** [comment]
Somewhat unfortunate, because it makes the root messier, but alas. Weird though, that it doesn't seem to pick up the change in this PR and run the action.

**Comment by DaanDeMeyer** [comment]
Its an error in the action path, let me try something else.

**Comment by DaanDeMeyer** [comment]
It's working, let's merge

**Comment by DaanDeMeyer** [comment]
@poettering @keszybz To release the mkosi Github Action (basically all the necessary shell hacks to get mkosi installed  on Github Actions vms along with building all relevant package managers (dnf/pacman) so it can be reused in other projects for CI and stuff), one of the systemd admins has to sign the GitHub Marketplace Developer Agreement. Is it possible to set that up? If you go to the draft new release page in the mkosi repo, you should see a prompt to sign it.

**Comment by poettering** [comment]
don#t know what precisely i agreed on there, but clicked on it now. hope this worked?

(btw, thanks a ton for all the mkosi work you are doing, much appreciated)

**Pull request merged**
