### PR TITLE
Ci tdnf

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by behrmann** [comment]
LGTM

**Comment by DaanDeMeyer** [comment]
The btrfs failure is pretty weird. I'll restart the builds to see if it's a fluke.

**Comment by DaanDeMeyer** [comment]
Disabled btrfs for now, uefi as well as the systemd-boot binaries don't seem to be at their default location in photon (or maybe not at all). (I should get some PKGBUILDs going for these niche package managers so I can test this stuff locally)

**Comment by DaanDeMeyer** [comment]
CI's green, let's merge.

**Pull request merged**
