### PR TITLE
Make sure the gpg agent is terminated even if an exception occurs

### PR DESCRIPTION
**Pull request by juergenhoetzel**
This prevents EBUSY exceptions when TemporaryDirectory finalizer is
invoked (#358).

### CODE REVIEW

**Comment by keszybz** [comment]
Can we please use a context manager for this?

**Comment by juergenhoetzel** [comment]
> Can we please use a context manager for this?

What kind of implementation with `@contextmanager`  do you have in mind?  Annotating `install_arch` would  mean that the implementation of `install_distribution` (using `with`) and all other `install_*`  functions (also use `contextmanager`)  would have to be changed.

**Comment by behrmann** [comment]
The idea, I think, would be to make some function `cleanup_gpg` (or similarly named) that is annotated with `@contextlib.contextmanager` and wraps this try-block such that it yields after the try and does the cleanup in the finally-clause, see `mount_image` for an example.

**Comment by DaanDeMeyer** [comment]
Superseded by #441

**Pull request closed without merging**
