### PR TITLE
make sure mkfs randomises its UUID

### PR DESCRIPTION
**Pull request by 257**

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
We should already be using randomized uuids since we remove the machine id before running repart. Are you running into cases where this is not happening?

**Comment by 257** [comment]
yes, almost 90% failure here. but i realise we don't hit this with CI.

**Comment by 257** [comment]
> We should already be using randomized uuids since we remove the machine id before running repart.

hmm, let me dig a bit deeper, i might be a local problem at my end.

**Comment by DaanDeMeyer** [comment]
If you see "No machine ID set, using randomized partition UUIDs." in the mkosi outputs, it should be using randomized UUIDs, if it isn't, that's a bug in systemd-repart

**Comment by keszybz** [comment]
@257 did you figure this one out?

**Comment by 257** [comment]
> @257 did you figure this one out?

yes

**Pull request closed without merging**
