### PR TITLE
mkosi: generate default UTF-8 locale for Arch Linux

### PR DESCRIPTION
**Pull request by johnlinp**
Fixes: #186

### CODE REVIEW

**Comment by poettering** [comment]
grrr. A pity that arch doesn't get this right out-of-the-box

**Comment by poettering** [comment]
hmm, this approach leaves locale-gen.service around in the image. I'd prefer if we didn't. Can't we instead just invoke localegen through nspawn, after running the package manager?

**Comment by johnlinp** [comment]
@poettering Thank you for the comments. I will work on it.

**Comment by johnlinp** [comment]
In the new patch, I use `run_workspace_command()` to execute `locale-gen` instead of creating a service unit. Please take a look at it. Thanks.

**Pull request merged**
