### PR TITLE
arch: debug

### PR DESCRIPTION
**Pull request by DaanDeMeyer**

### CODE REVIEW

**Comment by jre21** [comment]
I've run into issues similar to this in the past (Arch Linux can't find a PGP key it needs to import).  I've usually worked around it by [changing pacman's configured key server](https://wiki.archlinux.org/title/Pacman/Package_signing#Change_keyserver).

**Comment by jre21** [comment]
Another possibly-relevant oddity: mkosi appears to be setting the pacman keyring to a directory [outside the image root](https://github.com/systemd/mkosi/blob/fde6e2e264193600e105ab383775c6a51e7473f8/mkosi/__init__.py#L2981).

**Comment by DaanDeMeyer** [comment]
> Another possibly-relevant oddity: mkosi appears to be setting the pacman keyring to a directory [outside the image root](https://github.com/systemd/mkosi/blob/fde6e2e264193600e105ab383775c6a51e7473f8/mkosi/__init__.py#L2981).

That's intentional. It saves a lot of time rebuilding the keyring on every build.

**Comment by DaanDeMeyer** [comment]
This is fixed by #1084 so closing

**Pull request closed without merging**
