### PR TITLE
config: right strip newlines from contents read via path_read_text

### PR DESCRIPTION
**Pull request by behrmann**
This is an attempted fix for #2031. I'm not super happy about possible fallout from this, because of the silent stripping of newlines, but let's see whether this works. @NekkoDroid could you have a look whether this solves your issue?

### CODE REVIEW

**Comment by NekkoDroid** [comment]
I just tested it (without symlink as in the readme, testing again with) and it failed with the following traceback:

```
‣    Creating cpio archive /home/nekko/Documents/mkosi/mkosi.workspace/.mkosi-tmpbzxe3wr0/staging/image-initrd_0.1.cpio…
‣    Compressing /home/nekko/Documents/mkosi/mkosi.workspace/.mkosi-tmpbzxe3wr0/staging/image-initrd_0.1.cpio
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nekko/Documents/mkosi-git/mkosi/__main__.py", line 60, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/nekko/Documents/mkosi-git/mkosi/__main__.py", line 52, in main
    run_verb(args, images)
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 2710, in run_verb
    build_image(args, config)
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 2155, in build_image
    install_uki(state, partitions)
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 1356, in install_uki
    initrds = state.config.initrds.copy() or [build_initrd(state)]
                                              ^^^^^^^^^^^^^^^^^^^
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 1158, in build_initrd
    build_image(args, config)
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 2191, in build_image
    print_output_size(config.output_dir_or_cwd() / config.output)
  File "/home/nekko/Documents/mkosi-git/mkosi/__init__.py", line 1542, in print_output_size
    size = format_bytes(path.stat().st_size)
                        ^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/nekko/Documents/mkosi/mkosi.workspace/.mkosi-tmpoukucqe2/initrd/image-initrd'
```

**Comment by behrmann** [comment]
Can you provide the full config for this?

**Comment by NekkoDroid** [comment]
Files:

`/mkosi.conf`:

```
[Distribution]
Distribution=arch

[Content]
Packages=
    linux
    linux-firmware
    systemd
    systemd-sysvcompat
```

`/mkosi.version`:

```
0.1
```

Folders (all empty):
`/mkosi.builddir`
`/mkosi.cache`
`/mkosi.output`
`/mkosi.workspace`

**Comment by keszybz** [comment]
A test case would be nice. Especially one that fails before the patch is applied and succeeds afterwards.

**Comment by NekkoDroid** [comment]
Currently it seems (for my case at least) this patch actually causes a different problem. The config I provided causes the problem with the current version (and newest git). If I remove the `/mkosi.version` I am able to build the image successfully.

But with the current patch applied I get the error above. I am not too well veresed in python to know what exactly is causing the error and I would love to figure out what is causing that.

There is https://github.com/systemd/mkosi/blob/main/tests/test_config.py#L183 testing the output of the file (although the `mkosi.version` is created in code and without new-line, https://github.com/systemd/mkosi/blob/main/tests/test_config.py#L156). So adding a `\n` in L156 should in theory extend that testcase to cover this.

**Comment by NekkoDroid** [comment]
Actually, my statement of "and newest git" is inaccurate, I tested https://github.com/behrmann/mkosi/tree/master which is an older commit. I now tested it again with systemd/mkosi:main and I get the same error as I mentioned here: https://github.com/systemd/mkosi/pull/2038#issuecomment-1791579587

**Comment by NekkoDroid** [comment]
I just manually applied this patch to https://github.com/systemd/mkosi/commit/0ffac0b692e38efb70c192ab240fcbb09574cb67 (commit of the latest release) and I am successfully able to build with the above config, the commit itself seems to address the linked issue.

**Comment by DaanDeMeyer** [comment]
@NekkoDroid The other issue you were seeing on main should be fixed by https://github.com/systemd/mkosi/pull/2039

**Pull request merged**
